# Written by Gradle (build.gradle, processResources) from gradle.properties; read by com.brasshaven.release.BuildInfo.
version=${mod_version}
protocol=${network_protocol}
download_url=${mod_download_url}
