package com.wayfarers.world;

import com.wayfarers.Wayfarers;
import com.wayfarers.config.WayfarersConfig;
import net.minecraft.network.chat.Component;
import net.minecraft.server.packs.PackLocationInfo;
import net.minecraft.server.packs.PackSelectionConfig;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.PathPackResources;
import net.minecraft.server.packs.repository.Pack;
import net.minecraft.server.packs.repository.PackSource;
import net.minecraftforge.event.AddPackFindersEvent;
import net.minecraftforge.fml.ModList;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;

/**
 * Offers the world overhaul (terrain, caves, biomes) as a built-in data pack shipped inside the jar
 * (generated by tools/gen_world.py into worldgen_pack/). With {@code world.overhaul = true} it is a built-in pack,
 * ticked for every new world; with {@code false} it is a feature pack: listed, but off unless the player ticks it.
 */
public final class WorldOverhaul {
    public static final String PACK_ID = Wayfarers.MODID + ":world_overhaul";

    private WorldOverhaul() {}

    public static void addPacks(AddPackFindersEvent event) {
        if (event.getPackType() != PackType.SERVER_DATA) {
            return;
        }
        Path root = ModList.getModFileById(Wayfarers.MODID).getFile().findResource("worldgen_pack");
        if (!Files.isDirectory(root)) {
            Wayfarers.LOGGER.warn("World overhaul pack missing from the jar ({})", root);
            return;
        }
        boolean on = WayfarersConfig.WORLD_OVERHAUL.get();
        PackLocationInfo info = new PackLocationInfo(PACK_ID, Component.translatable("pack.wayfarers.world_overhaul"),
                on ? PackSource.BUILT_IN : PackSource.FEATURE, Optional.empty());
        Pack pack = Pack.readMetaAndCreate(info, new PathPackResources.PathResourcesSupplier(root), PackType.SERVER_DATA,
                new PackSelectionConfig(false, Pack.Position.TOP, false));
        if (pack != null) {
            event.addRepositorySource(consumer -> consumer.accept(pack));
        }
    }
}
