package com.brasshaven.accessory;

import com.brasshaven.Brasshaven;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import org.jetbrains.annotations.Nullable;

/**
 * The kinds of accessory slot. Which items fit is an item tag per kind ({@code brasshaven:accessory/<id>}, generated by
 * tools/wf/accessories.py), so a datapack or another mod can add items to a slot.
 */
public enum AccessorySlotType {
    BACK("back"), RING("ring"), AMULET("amulet"), BELT("belt");

    /** The slots of a player, top to bottom (the same order as accessories.LAYOUT in Python). */
    public static final AccessorySlotType[] LAYOUT = {BACK, RING, RING, AMULET, BELT};

    public final String id;
    public final TagKey<Item> tag;
    /** Empty-slot silhouette (GUI atlas sprite, gen_gui.py). */
    public final Identifier icon;

    AccessorySlotType(String id) {
        this.id = id;
        this.tag = TagKey.create(Registries.ITEM, Brasshaven.id("accessory/" + id));
        this.icon = Brasshaven.id("accessory/" + id);
    }

    public boolean fits(ItemStack stack) {
        return !stack.isEmpty() && stack.is(tag);
    }

    public Component label() {
        return Component.translatable("tooltip.brasshaven.accessory.slot." + id);
    }

    /** The slot kind an item is worn in, or null for anything that is not an accessory. */
    public static @Nullable AccessorySlotType of(ItemStack stack) {
        for (AccessorySlotType type : values()) {
            if (type.fits(stack)) {
                return type;
            }
        }
        return null;
    }
}
