"""Single source of truth for every Wayfarers id and its names (fr_fr / en_us).

gen_assets.py turns this into models, blockstates and lang files; validate.py checks
that the Java registries declare exactly these ids.
"""

# id -> (english name, french name, english tooltip, french tooltip)
ITEMS = {
    "map_fragment": ("Map Fragment", "Fragment de carte",
                     "Torn piece of an ancient map. Found in Overworld ruins.",
                     "Morceau d'une carte ancienne. Se trouve dans les ruines de la Surface."),
    "lithite_shard": ("Lithite Shard", "Éclat de lithite",
                      "A crystal that hums deep underground.",
                      "Un cristal qui vibre dans les profondeurs."),
    "ancient_ember": ("Ancient Ember", "Braise ancienne",
                      "Still warm after a thousand years in the Nether.",
                      "Encore tiède après mille ans dans le Nether."),
    "void_shard": ("Void Shard", "Éclat du vide", "A sliver of the space between the End islands.",
                   "Un fragment de l'espace entre les îles de l'End."),
    "warden_scale": ("Drowned Warden Scale", "Écaille du Gardien englouti",
                     "Trophy of the Sunken Citadel.", "Trophée de la Citadelle engloutie."),
    "void_heart": ("Void Heart", "Cœur du vide", "It beats with the rhythm of the void.",
                   "Il bat au rythme du vide."),
    "wayfarer_atlas": ("Wayfarer's Atlas", "Atlas du Voyageur",
                       "Use: show your guild's journey. [L] opens the full quest map.",
                       "Clic droit : progression de la guilde. [L] ouvre la carte des quêtes."),
    "structure_compass": ("Structure Compass", "Boussole des structures",
                          "Use: locate the nearest unexplored Wayfarers structure. Sneak-use: change target.",
                          "Clic droit : trouve la structure la plus proche. Accroupi : change de cible."),
    "travel_backpack": ("Travel Backpack", "Sac du Voyageur", "Use: open 27 extra slots that travel with you.",
                        "Clic droit : 27 emplacements qui voyagent avec toi."),
    "magnet_ring": ("Magnet Ring", "Anneau aimanté", "Pulls nearby items while in your inventory. Use: toggle.",
                    "Attire les objets proches depuis l'inventaire. Clic droit : activer/désactiver."),
    "recall_scroll": ("Recall Scroll", "Parchemin de rappel", "Use: return to your bed or world spawn.",
                      "Clic droit : retour à ton lit ou au point d'apparition."),
    "cartographer_blade": ("Cartographer's Blade", "Lame du Cartographe", "Use: dash forward.",
                           "Clic droit : ruée vers l'avant."),
    "telluric_hammer": ("Telluric Hammer", "Marteau tellurique", "Use: shockwave that knocks enemies back.",
                        "Clic droit : onde de choc qui repousse les ennemis."),
    "storm_staff": ("Storm Staff", "Bâton des tempêtes", "Use: call lightning where you look.",
                    "Clic droit : appelle la foudre là où tu regardes."),
    "ember_scythe": ("Ember Scythe", "Faux de braise", "Sets foes ablaze. Heals you in the Nether.",
                     "Enflamme les ennemis. Te soigne dans le Nether."),
    "void_spear": ("Void Spear", "Lance du vide", "Use: blink behind the creature you look at.",
                   "Clic droit : téléportation derrière la cible visée."),
    "boomerang": ("Boomerang", "Boomerang", "Use: throw. It comes back!", "Clic droit : lancer. Il revient !"),
    "frost_blade": ("Frost Blade", "Lame de givre", "Slows foes; every third hit freezes them.",
                    "Ralentit ; un coup sur trois gèle la cible."),
    "light_staff": ("Staff of Dawn", "Bâton de l'aube", "Use: burst of light that repels monsters.",
                    "Clic droit : éclat de lumière qui repousse les monstres."),
    "excavator_pickaxe": ("Excavator Pickaxe", "Pioche d'excavation", "Mines 3x3. Sneak to mine one block.",
                          "Mine en 3x3. Accroupi : un seul bloc."),
    "lumber_axe": ("Lumber Axe", "Hache de bûcheron", "Fells whole trees. Sneak to cut one log.",
                   "Abat l'arbre entier. Accroupi : une seule bûche."),
}
ARMOR_SETS = {
    "explorer": ("Explorer", "d'explorateur", "Set: Speed, no fall damage below 8 blocks, night vision underground.",
                 "Ensemble : vitesse, pas de dégâts de chute sous 8 blocs, vision nocturne sous terre."),
    "ember": ("Ember", "de braise", "Set: fire immunity and faster in lava.",
              "Ensemble : immunité au feu et plus rapide dans la lave."),
    "void": ("Void", "du vide", "Set: slow fall, and the void sends you back instead of killing you.",
             "Ensemble : chute lente, et le vide te ramène au lieu de te tuer."),
}
PIECES = {"helmet": ("Helmet", "Casque"), "chestplate": ("Chestplate", "Plastron"),
          "leggings": ("Leggings", "Jambières"), "boots": ("Boots", "Bottes")}
for _set, (en, fr, ten, tfr) in ARMOR_SETS.items():
    for _p, (pen, pfr) in PIECES.items():
        ITEMS[f"{_set}_{_p}"] = (f"{en} {pen}", f"{pfr} {fr}", ten, tfr)

# block id -> (english, french, tooltip en, tooltip fr, model kind)
BLOCKS = {
    "waystone": ("Waystone", "Pierre de voyage",
                 "Use: warp to any waystone your group discovered. Shared by every player.",
                 "Clic droit : voyage vers toute pierre découverte par le groupe.", "waystone"),
    "sorting_chest": ("Sorting Chest", "Coffre de tri", "54 slots. Sorts itself and vacuums nearby items.",
                      "54 emplacements. Se trie seul et aspire les objets proches.", "column"),
    "guild_terminal": ("Guild Terminal", "Terminal de guilde",
                       "Use: deposit your inventory into nearby chests. Sneak-use: sort them all.",
                       "Clic droit : range ton inventaire dans les coffres proches. Accroupi : trie tout.",
                       "front"),
    "grave": ("Grave", "Tombe", "Holds the belongings of a fallen wayfarer.",
              "Garde les affaires d'un voyageur tombé.", "grave"),
    "sealed_bars": ("Sealed Bars", "Barreaux scellés", "Opens when the guardian falls.",
                    "S'ouvre quand le gardien tombe.", "cube"),
    "warden_altar": ("Drowned Warden Altar", "Autel du Gardien englouti", "Use with a Map Fragment to awaken it.",
                     "Utilise un fragment de carte pour le réveiller.", "column"),
    "void_altar": ("Void Altar", "Autel du vide", "Use with a Void Shard to awaken the Void Warden.",
                   "Utilise un éclat du vide pour réveiller le Gardien du vide.", "column"),
    "lithite_ore": ("Lithite Ore", "Minerai de lithite", "", "", "cube"),
    "deepslate_lithite_ore": ("Deepslate Lithite Ore", "Minerai de lithite des abîmes", "", "", "cube"),
}

# entity id -> (english, french)
ENTITIES = {
    "ruin_walker": ("Ruin Walker", "Rôdeur des ruines"),
    "map_wraith": ("Map Wraith", "Spectre des cartes"),
    "basalt_guard": ("Basalt Guard", "Garde de basalte"),
    "void_stalker": ("Void Stalker", "Traqueur du vide"),
    "drowned_warden": ("Drowned Warden", "Gardien englouti"),
    "void_warden": ("Void Warden", "Gardien du vide"),
    "boomerang": ("Boomerang", "Boomerang"),
}
SPAWN_EGGS = ["ruin_walker", "map_wraith", "basalt_guard", "void_stalker", "drowned_warden", "void_warden"]

# Misc translated messages used from Java (key suffix -> (en, fr))
MESSAGES = {
    "itemGroup.wayfarers": ("Wayfarers", "Wayfarers"),
    "key.category.wayfarers.main": ("Wayfarers", "Wayfarers"),
    "key.wayfarers.sort_inventory": ("Sort inventory", "Trier l'inventaire"),
    "key.wayfarers.toggle_magnet": ("Toggle magnet ring", "Activer/désactiver l'aimant"),
    "message.wayfarers.welcome": ("Welcome, wayfarer! Your Atlas tracks the guild's journey — press [L] to see every quest.",
                                  "Bienvenue, voyageur ! Ton Atlas suit le voyage de la guilde — appuie sur [L] pour voir toutes les quêtes."),
    "message.wayfarers.shared": ("%s completed \"%s\" for the whole guild!", "%s a accompli « %s » pour toute la guilde !"),
    "message.wayfarers.atlas.header": ("== Guild journey ==", "== Voyage de la guilde =="),
    "message.wayfarers.atlas.chapter": ("%s: %s/%s", "%s : %s/%s"),
    "message.wayfarers.atlas.next": ("Next goal: %s", "Prochain objectif : %s"),
    "message.wayfarers.atlas.done": ("Every chapter is complete. Legendary!", "Tous les chapitres sont terminés. Légendaire !"),
    "message.wayfarers.compass.target": ("Compass target: %s", "Cible de la boussole : %s"),
    "message.wayfarers.compass.found": ("%s: %s blocks %s (x %s, z %s)", "%s : %s blocs vers %s (x %s, z %s)"),
    "message.wayfarers.compass.none": ("No %s nearby in this dimension.", "Aucun(e) %s à proximité dans cette dimension."),
    "message.wayfarers.compass.any": ("any structure", "n'importe quelle structure"),
    "message.wayfarers.waystone.discovered": ("Waystone discovered: %s (shared with everyone)",
                                              "Pierre de voyage découverte : %s (partagée avec tout le monde)"),
    "message.wayfarers.waystone.list": ("Waystones — click to travel:", "Pierres de voyage — clique pour voyager :"),
    "message.wayfarers.waystone.entry": ("[%s] %s (%s)", "[%s] %s (%s)"),
    "message.wayfarers.waystone.none": ("No other waystone discovered yet.", "Aucune autre pierre découverte pour l'instant."),
    "message.wayfarers.waystone.travel": ("Whoosh! Welcome to %s.", "Fiouuu ! Bienvenue à %s."),
    "message.wayfarers.waystone.unknown": ("That waystone no longer exists.", "Cette pierre de voyage n'existe plus."),
    "message.wayfarers.waystone.hover": ("Click to travel", "Clique pour voyager"),
    "message.wayfarers.terminal.deposit": ("Stored %s items in %s chests.", "%s objets rangés dans %s coffres."),
    "message.wayfarers.terminal.sorted": ("Sorted %s chests.", "%s coffres triés."),
    "message.wayfarers.terminal.nothing": ("No chest within %s blocks.", "Aucun coffre à moins de %s blocs."),
    "message.wayfarers.grave": ("Your belongings rest in a grave at %s %s %s (%s).",
                                "Tes affaires reposent dans une tombe en %s %s %s (%s)."),
    "message.wayfarers.grave.restored": ("Belongings recovered.", "Affaires récupérées."),
    "message.wayfarers.magnet.on": ("Magnet on", "Aimant activé"),
    "message.wayfarers.magnet.off": ("Magnet off", "Aimant désactivé"),
    "message.wayfarers.recall": ("Recalled home.", "Retour à la maison."),
    "message.wayfarers.sorted": ("Inventory sorted.", "Inventaire trié."),
    "message.wayfarers.altar.need": ("The altar needs %s.", "L'autel réclame : %s."),
    "message.wayfarers.altar.awake": ("%s awakens!", "%s se réveille !"),
    "message.wayfarers.boss.defeated": ("%s has been defeated! The sealed bars crumble.",
                                        "%s est vaincu ! Les barreaux scellés s'effondrent."),
    "message.wayfarers.void_saved": ("The void spits you back out.", "Le vide te recrache."),
    "message.wayfarers.cooldown": ("Recharging...", "Recharge..."),
    "message.wayfarers.kit": ("Kit '%s' given.", "Kit « %s » donné."),
    "message.wayfarers.progress.reset": ("Wayfarers progression reset.", "Progression Wayfarers réinitialisée."),
    "message.wayfarers.progress.complete": ("Every Wayfarers quest granted.", "Toutes les quêtes Wayfarers accordées."),
    "message.wayfarers.locate": ("%s is at %s, %s (%s blocks).", "%s se trouve en %s, %s (%s blocs)."),
    "chapter.wayfarers.first_steps": ("I. First Steps", "I. Premiers pas"),
    "chapter.wayfarers.explorer": ("II. Overworld Explorer", "II. Explorateur de la Surface"),
    "chapter.wayfarers.depths": ("III. The Depths", "III. Les profondeurs"),
    "chapter.wayfarers.nether": ("IV. The Nether", "IV. Le Nether"),
    "chapter.wayfarers.end": ("V. The End", "V. L'End"),
    "message.wayfarers.elite": ("Elite %s", "%s d'élite"),
    "message.wayfarers.blood_moon.rise": ("The Blood Moon rises... monsters grow restless and strong. Stay together!",
                                          "La lune de sang se lève... les monstres deviennent enragés. Restez groupés !"),
    "message.wayfarers.blood_moon.end": ("Dawn breaks: the Blood Moon fades.", "L'aube se lève : la lune de sang s'efface."),
    "message.wayfarers.danger": ("Danger: %s", "Danger : %s"),
    "message.wayfarers.danger.0": ("Safe", "Sûr"),
    "message.wayfarers.danger.1": ("Low", "Faible"),
    "message.wayfarers.danger.2": ("Moderate", "Modéré"),
    "message.wayfarers.danger.3": ("High", "Élevé"),
    "message.wayfarers.danger.4": ("Severe", "Sévère"),
    "message.wayfarers.danger.5": ("Extreme", "Extrême"),
    "message.wayfarers.danger.6": ("Deadly", "Mortel"),
    "message.wayfarers.danger.7": ("Legendary", "Légendaire"),
    "tooltip.wayfarers.set_bonus": ("Full set bonus:", "Bonus d'ensemble complet :"),
    "tooltip.wayfarers.magnet.on": ("Active", "Actif"),
    "tooltip.wayfarers.magnet.off": ("Inactive", "Inactif"),
}
