"""Single source of truth for every Wayfarers id and its names (fr_fr / en_us).

gen_assets.py turns this into models, blockstates and lang files; validate.py checks
that the Java registries declare exactly these ids.
"""

# id -> (english name, french name, english tooltip, french tooltip)
ITEMS = {
    "map_fragment": ("Map Fragment", "Fragment de carte",
                     "Torn piece of an ancient map. Found in Overworld ruins.",
                     "Morceau d'une carte ancienne. Se trouve dans les ruines de la Surface."),
    "lithite_shard": ("Lithite Shard", "Éclat de lithite",
                      "A crystal that hums deep underground.",
                      "Un cristal qui vibre dans les profondeurs."),
    "ancient_ember": ("Ancient Ember", "Braise ancienne",
                      "Still warm after a thousand years in the Nether.",
                      "Encore tiède après mille ans dans le Nether."),
    "void_shard": ("Void Shard", "Éclat du vide", "A sliver of the space between the End islands.",
                   "Un fragment de l'espace entre les îles de l'End."),
    "warden_scale": ("Drowned Warden Scale", "Écaille du Gardien englouti",
                     "Trophy of the Sunken Citadel.", "Trophée de la Citadelle engloutie."),
    "void_heart": ("Void Heart", "Cœur du vide", "It beats with the rhythm of the void.",
                   "Il bat au rythme du vide."),
    "brass_gear": ("Brass Gear", "Engrenage en laiton",
                   "A precise little cog salvaged from an automaton.",
                   "Un petit engrenage de précision récupéré sur un automate."),
    "clockwork_heart": ("Clockwork Heart", "Cœur mécanique",
                        "Use it on two stacked Blocks of Brass to wake a Brass Golem that follows you.",
                        "Utilise-le sur deux blocs de laiton empilés pour réveiller un golem de laiton qui te suit."),
    "wayfarer_atlas": ("Wayfarer's Atlas", "Atlas du Voyageur",
                       "Use (or press J): open the quest journal. Sneak-use (or press M): the world map.",
                       "Clic droit (ou touche J) : journal de quêtes. Accroupi (ou touche M) : carte du monde."),
    "wayfarer_manual": ("Wayfarer's Manual", "Manuel du Voyageur",
                        "Use: learn how every Wayfarers system works. Hold the manual key (W) over an item: its page.",
                        "Clic droit : comment fonctionne chaque système. Touche du manuel (Z en AZERTY) sur un objet : sa page."),
    "fire_staff": ("Fire Staff", "Bâton de feu", "Spell (15 mana): a fire bolt that sets the target ablaze.",
                   "Sort (15 mana) : un trait de feu qui enflamme la cible."),
    "frost_staff": ("Frost Staff", "Bâton de givre", "Spell (25 mana): a frost nova that freezes and slows foes around you.",
                    "Sort (25 mana) : une nova de givre qui gèle et ralentit les ennemis autour de toi."),
    "thunder_staff": ("Tesla Staff", "Bâton Tesla", "Spell (35 mana): lightning that jumps between up to 4 foes.",
                      "Sort (35 mana) : un éclair qui rebondit entre 4 ennemis."),
    "healing_staff": ("Staff of Mending", "Bâton de soin", "Spell (30 mana): heals you and the players around you.",
                      "Sort (30 mana) : te soigne, toi et les joueurs autour."),
    "levitation_wand": ("Levitation Wand", "Baguette de lévitation",
                        "Spell (20 mana): lifts the creature you aim at. Sneak: slow fall for yourself.",
                        "Sort (20 mana) : soulève la créature visée. Accroupi : chute lente pour toi."),
    "ward_orb": ("Ward Orb", "Orbe de protection", "Spell (40 mana): an arcane shield that absorbs damage.",
                 "Sort (40 mana) : un bouclier arcanique qui absorbe les dégâts."),
    "steam_cane": ("Steam Cane", "Canne à vapeur", "Spell (20 mana): a blast of steam that hurls foes back.",
                   "Sort (20 mana) : un jet de vapeur qui repousse les ennemis."),
    "arcane_ring": ("Arcane Ring", "Anneau arcanique", "Carry it: +50 max mana.", "À garder sur toi : +50 de mana max."),
    "mana_amulet": ("Mana Amulet", "Amulette de mana", "Carry it: mana regenerates 50% faster.",
                    "À garder sur toi : le mana se régénère 50 % plus vite."),
    "oblivion_vial": ("Vial of Oblivion", "Fiole d'oubli", "Use: forget every talent and get all your points back.",
                      "Clic droit : oublie tous tes talents et récupère tous tes points."),
    "builder_wand": ("Builder's Wand", "Baguette du bâtisseur",
                     "Use on a block: extend that face by up to 16 blocks from your inventory. Sneak-use in the air: undo. "
                     "Sneak-use a block: mirror centre; G: symmetry mode.",
                     "Clic droit sur un bloc : prolonge la face de 16 blocs max (pris dans l'inventaire). Accroupi dans "
                     "le vide : annuler. Accroupi sur un bloc : centre du miroir ; G : mode symétrie."),
    "master_builder_wand": ("Master Builder's Wand", "Baguette du maître bâtisseur",
                            "Use on a block: extend that face by up to 64 blocks. Sneak-use in the air: undo. "
                            "Sneak-use a block: mirror centre; G: symmetry mode.",
                            "Clic droit sur un bloc : prolonge la face de 64 blocs max. Accroupi dans le vide : annuler. "
                            "Accroupi sur un bloc : centre du miroir ; G : mode symétrie."),
    "chisel": ("Engraver's Chisel", "Burin du graveur",
               "Use on a block: turn it into the next variant of its family (stone bricks, mossy, cracked, chiseled...). "
               "Sneak-use: previous variant. Stairs and slabs keep their shape.",
               "Clic droit sur un bloc : le transforme en la variante suivante de sa famille (briques, moussues, "
               "fissurées, sculptées...). Accroupi : variante précédente. Escaliers et dalles gardent leur forme."),
    "structure_compass": ("Structure Compass", "Boussole des structures",
                          "Use: locate the nearest Wayfarers structure. Sneak-use: change target.",
                          "Clic droit : trouve la structure la plus proche. Accroupi : change de cible."),
    "explorer_backpack": ("Explorer's Backpack", "Sac de l'Explorateur",
                          "Use: 54 extra slots. Craft it from a Travel Backpack and a brass ingot: nothing inside is lost.",
                          "Clic droit : 54 emplacements. Se fabrique avec un Sac du Voyageur et un lingot de laiton, sans rien perdre du contenu."),
    "travel_backpack": ("Travel Backpack", "Sac du Voyageur", "Use: open 27 extra slots that travel with you.",
                        "Clic droit : 27 emplacements qui voyagent avec toi."),
    "magnet_ring": ("Magnet Ring", "Anneau aimanté", "Pulls nearby items while in your inventory. Use: toggle.",
                    "Attire les objets proches depuis l'inventaire. Clic droit : activer/désactiver."),
    "recall_scroll": ("Recall Scroll", "Parchemin de rappel", "Use: return to the nearest waystone of this dimension.",
                      "Clic droit : retour à la pierre de voyage la plus proche de cette dimension."),
    "cartographer_blade": ("Cartographer's Blade", "Lame du Cartographe", "Use: dash forward.",
                           "Clic droit : ruée vers l'avant."),
    "telluric_hammer": ("Telluric Hammer", "Marteau tellurique", "Use: shockwave that knocks enemies back.",
                        "Clic droit : onde de choc qui repousse les ennemis."),
    "storm_staff": ("Storm Staff", "Bâton des tempêtes", "Use: call lightning where you look.",
                    "Clic droit : appelle la foudre là où tu regardes."),
    "ember_scythe": ("Ember Scythe", "Faux de braise", "Sets foes ablaze. Heals you in the Nether.",
                     "Enflamme les ennemis. Te soigne dans le Nether."),
    "void_spear": ("Void Spear", "Lance du vide", "Use: blink behind the creature you look at.",
                   "Clic droit : téléportation derrière la cible visée."),
    "boomerang": ("Boomerang", "Boomerang", "Use: throw. It comes back!", "Clic droit : lancer. Il revient !"),
    "frost_blade": ("Frost Blade", "Lame de givre", "Slows foes; every third hit freezes them.",
                    "Ralentit ; un coup sur trois gèle la cible."),
    "light_staff": ("Staff of Dawn", "Bâton de l'aube", "Use: burst of light that repels monsters.",
                    "Clic droit : éclat de lumière qui repousse les monstres."),
    "excavator_pickaxe": ("Excavator Pickaxe", "Pioche d'excavation", "Mines 3x3. Sneak to mine one block.",
                          "Mine en 3x3. Accroupi : un seul bloc."),
    "lumber_axe": ("Lumber Axe", "Hache de bûcheron", "Fells whole trees. Sneak to cut one log.",
                   "Abat l'arbre entier. Accroupi : une seule bûche."),
}
ARMOR_SETS = {
    "explorer": ("Explorer", "d'explorateur", "Set: Speed, no fall damage below 8 blocks, night vision underground.",
                 "Ensemble : vitesse, pas de dégâts de chute sous 8 blocs, vision nocturne sous terre."),
    "ember": ("Ember", "de braise", "Set: fire immunity and faster in lava.",
              "Ensemble : immunité au feu et plus rapide dans la lave."),
    "void": ("Void", "du vide", "Set: slow fall, and the void sends you back instead of killing you.",
             "Ensemble : chute lente, et le vide te ramène au lieu de te tuer."),
}
PIECES = {"helmet": ("Helmet", "Casque"), "chestplate": ("Chestplate", "Plastron"),
          "leggings": ("Leggings", "Jambières"), "boots": ("Boots", "Bottes")}
for _set, (en, fr, ten, tfr) in ARMOR_SETS.items():
    for _p, (pen, pfr) in PIECES.items():
        ITEMS[f"{_set}_{_p}"] = (f"{en} {pen}", f"{pfr} {fr}", ten, tfr)

# block id -> (english, french, tooltip en, tooltip fr, model kind)
BLOCKS = {
    "waystone": ("Waystone", "Pierre de voyage",
                 "Right-click: open the travel map to any waystone your group discovered.",
                 "Clic droit : ouvre la carte de voyage vers toute pierre découverte par le groupe.", "waystone"),
    "sorting_chest": ("Sorting Chest", "Coffre de tri", "54 slots. Sorts itself and vacuums nearby items.",
                      "54 emplacements. Se trie seul et aspire les objets proches.", "column"),
    "guild_terminal": ("Guild Terminal", "Terminal de guilde",
                       "Use: every chest of your base (48 blocks around, more with Storage Relays) in one searchable grid.",
                       "Clic droit : tous les coffres de ta base (48 blocs autour, plus avec des relais) dans une grille.",
                       "front"),
    "storage_relay": ("Storage Relay", "Relais de stockage",
                      "Extends a Guild Terminal: links every chest 32 blocks around. Place it within reach of the terminal or of another relay.",
                      "Étend un terminal de guilde : relie les coffres à 32 blocs. À poser à portée du terminal ou d'un autre relais.",
                      "column"),
    "compacting_crate": ("Compacting Crate", "Caisse compacte",
                         "Holds 32 stacks of one item, shown on its front. Right-click: put in (twice quickly: all you carry). Left-click: take a stack.",
                         "32 piles d'un seul objet, affiché en façade. Clic droit : ranger (deux fois vite : tout). Clic gauche : prendre une pile.",
                         "front"),
    "grave": ("Grave", "Tombe", "Holds the belongings of a fallen wayfarer.",
              "Garde les affaires d'un voyageur tombé.", "grave"),
    "sealed_bars": ("Sealed Bars", "Barreaux scellés", "Opens when the guardian falls.",
                    "S'ouvre quand le gardien tombe.", "cube"),
    "warden_altar": ("Drowned Warden Altar", "Autel du Gardien englouti", "Use with a Map Fragment to awaken it.",
                     "Utilise un fragment de carte pour le réveiller.", "column"),
    "void_altar": ("Void Altar", "Autel du vide", "Use with a Void Shard to awaken the Void Warden.",
                   "Utilise un éclat du vide pour réveiller le Gardien du vide.", "column"),
    "mist_gate": ("Boss Mist", "Brume du gardien",
                  "Walk through it to face the boss; it seals behind you until the fight ends.",
                  "Traverse-la pour affronter le gardien ; elle se referme jusqu'à la fin du combat.", "mist"),
    "boss_seal": ("Boss Seal", "Sceau du gardien", "Heart of a boss arena (placed by dungeons): the boss wakes when you step inside.",
                  "Cœur d'une arène (posé par les donjons) : le gardien se réveille quand tu entres.", "column"),
    "chisel_table": ("Chisel Table", "Table de taille",
                     "Use: put a stack of blocks in, click a variant to turn the whole stack into it, for free.",
                     "Clic droit : pose une pile de blocs, clique une variante pour transformer toute la pile, gratuitement.",
                     "table"),
    "lithite_ore": ("Lithite Ore", "Minerai de lithite", "", "", "cube"),
    "deepslate_lithite_ore": ("Deepslate Lithite Ore", "Minerai de lithite des abîmes", "", "", "cube"),
}

# entity id -> (english, french)
ENTITIES = {
    "ruin_walker": ("Ruin Walker", "Rôdeur des ruines"),
    "map_wraith": ("Map Wraith", "Spectre des cartes"),
    "basalt_guard": ("Basalt Guard", "Garde de basalte"),
    "void_stalker": ("Void Stalker", "Traqueur du vide"),
    "drowned_warden": ("Drowned Warden", "Gardien englouti"),
    "void_warden": ("Void Warden", "Gardien du vide"),
    "skeleton_knight": ("Skeleton Knight", "Chevalier squelette"),
    "crypt_crawler": ("Crypt Crawler", "Rampant des cryptes"),
    "banshee": ("Banshee", "Banshee"),
    "gargoyle": ("Gargoyle", "Gargouille"),
    "ember_imp": ("Ember Imp", "Imp de braise"),
    "void_larva": ("Void Larva", "Larve du vide"),
    "grave_knight": ("The Grave Knight", "Le Chevalier des tombes"),
    "bone_matriarch": ("The Bone Matriarch", "La Matriarche d'os"),
    "weeping_lady": ("The Weeping Lady", "La Dame en pleurs"),
    "larva_mother": ("The Larva Mother", "La Mère-Larve"),
    "bell_keeper": ("The Bell Keeper", "Le Sonneur de glas"),
    "archivist": ("The Archivist", "L'Archiviste"),
    "sand_pharaoh": ("The Sand Pharaoh", "Le Pharaon ensablé"),
    "jade_jaguar": ("The Jade Jaguar", "Le Jaguar de jade"),
    "root_mother": ("The Root Mother", "La Mère-Racine"),
    "swamp_crone": ("The Swamp Crone", "La Grand-Mère du marais"),
    "gryphon_knight": ("The Gryphon Knight", "Le Chevalier-griffon"),
    "rune_colossus": ("The Rune Colossus", "Le Colosse runique"),
    "forge_king": ("The Forge King", "Le Roi-Forgeron"),
    "crystal_spider": ("The Crystal Matriarch", "La Matriarche de cristal"),
    "sculk_spawn": ("The Sculk Spawn", "Le Rejeton du sculk"),
    "ash_lord": ("The Ash Lord", "Le Seigneur des Cendres"),
    "piglin_king": ("The Golden Piglin King", "Le Roi piglin doré"),
    "soul_reaper": ("The Soul Reaper", "La Faucheuse des âmes"),
    "clockwork_spider": ("Clockwork Spider", "Araignée-horloge"),
    "steam_drone": ("Steam Drone", "Drone à vapeur"),
    "brass_golem": ("Brass Golem", "Golem de laiton"),
    "grand_clockmaker": ("The Grand Clockmaker", "Le Grand Horloger"),
    "hot_rivet": ("Hot Rivet", "Rivet brûlant"),
    "boomerang": ("Boomerang", "Boomerang"),
}
SPAWN_EGGS = ["ruin_walker", "map_wraith", "basalt_guard", "void_stalker", "drowned_warden", "void_warden",
              "bell_keeper",
              "archivist",
              "sand_pharaoh",
              "jade_jaguar",
              "root_mother",
              "swamp_crone",
              "gryphon_knight",
              "rune_colossus",
              "forge_king",
              "crystal_spider",
              "sculk_spawn",
              "ash_lord",
              "piglin_king",
              "soul_reaper",
              "skeleton_knight",
              "crypt_crawler",
              "banshee",
              "gargoyle",
              "ember_imp",
              "void_larva",
              "grave_knight",
              "bone_matriarch",
              "weeping_lady",
              "larva_mother",
              "clockwork_spider",
              "steam_drone",
              "brass_golem",
              "grand_clockmaker",
              ]

# Misc translated messages used from Java (key suffix -> (en, fr))
MESSAGES = {
    "message.wayfarers.crate.empty": ("Empty crate: put any item in to choose its kind.",
                                      "Caisse vide : range un objet pour choisir son type."),
    "message.wayfarers.crate.count": ("%s: %s / %s", "%s : %s / %s"),
    "pack.wayfarers.world_overhaul": ("Wayfarers: new world (terrain, caves, biomes)",
                                      "Wayfarers : nouveau monde (relief, grottes, biomes)"),
    "itemGroup.wayfarers": ("Wayfarers", "Wayfarers"),
    "key.category.wayfarers.main": ("Wayfarers", "Wayfarers"),
    "key.wayfarers.sort_inventory": ("Sort inventory", "Trier l'inventaire"),
    "key.wayfarers.toggle_magnet": ("Toggle magnet ring", "Activer/désactiver l'aimant"),
    "key.wayfarers.quests": ("Quest journal", "Journal de quêtes"),
    "key.wayfarers.skills": ("Talent tree", "Arbre de talents"),
    "key.wayfarers.ability": ("Use active talent", "Utiliser le talent actif"),
    "gui.wayfarers.skills.title": ("Talents", "Talents"),
    "gui.wayfarers.skills.points": ("Points: %s (earned: %s)", "Points : %s (gagnés : %s)"),
    "gui.wayfarers.skills.hint": ("Click a talent to unlock it", "Clique sur un talent pour le débloquer"),
    "gui.wayfarers.skills.points.tip": ("Quests, bosses and levels give talent points.",
                                        "Les quêtes, les boss et les niveaux donnent des points de talent."),
    "gui.wayfarers.skills.mana": ("Max mana: %s", "Mana max : %s"),
    "gui.wayfarers.skills.active": ("Active (%s): %s", "Actif (%s) : %s"),
    "gui.wayfarers.skills.cost": ("Cost: %s point(s)", "Coût : %s point(s)"),
    "gui.wayfarers.skills.owned": ("Unlocked", "Débloqué"),
    "gui.wayfarers.skills.click_equip": ("Unlocked - click to equip it on %s", "Débloqué - clic pour l'équiper sur %s"),
    "skill.wayfarers.ability.fury": ("Fury", "Fureur"),
    "skill.wayfarers.ability.dash": ("Dash", "Ruée"),
    "skill.wayfarers.ability.shield": ("Arcane Shield", "Bouclier arcanique"),
    "skill.wayfarers.ability.overdrive": ("Overdrive", "Surcharge"),
    "message.wayfarers.skill.point": ("New talent point! Press %s to spend it.", "Nouveau point de talent ! Appuie sur %s pour le dépenser."),
    "message.wayfarers.skill.no_active": ("No active talent yet: unlock a capstone talent (K).",
                                          "Aucun talent actif : débloque un talent ultime (K)."),
    "message.wayfarers.skill.cooldown": ("Ready in %ss", "Prêt dans %s s"),
    "message.wayfarers.skill.reset": ("Your talents fade away... every point is yours again.",
                                      "Tes talents s'effacent... tous tes points te sont rendus."),
    "message.wayfarers.mana.low": ("Not enough mana", "Pas assez de mana"),
    "gui.wayfarers.quests.title": ("Quest Journal", "Journal de quêtes"),
    "gui.wayfarers.manual.hold": ("Hold %s: manual page", "Maintiens %s : page du manuel"),
    "gui.wayfarers.settings.title": ("Wayfarers settings", "Réglages Wayfarers"),
    "gui.wayfarers.settings.health_bars": ("Health bars", "Barres de vie"),
    "gui.wayfarers.settings.health_bars.tip": ("Health bars above creatures.", "Barres de vie au-dessus des créatures."),
    "gui.wayfarers.settings.health_bars.always": ("Always", "Toujours"),
    "gui.wayfarers.settings.health_bars.always.tip": ("Above every creature nearby.", "Au-dessus de toutes les créatures proches."),
    "gui.wayfarers.settings.health_bars.damaged": ("Hurt", "Blessées"),
    "gui.wayfarers.settings.health_bars.damaged.tip": ("Above hurt creatures and the one you aim at.",
                                                       "Au-dessus des créatures blessées et de celle que tu vises."),
    "gui.wayfarers.settings.health_bars.never": ("Never", "Jamais"),
    "gui.wayfarers.settings.health_bars.never.tip": ("No health bars.", "Pas de barres de vie."),
    "gui.wayfarers.settings.damage_numbers": ("Damage numbers", "Chiffres de dégâts"),
    "gui.wayfarers.settings.damage_numbers.tip": ("Floating numbers when you hit a creature.",
                                                  "Chiffres qui s'envolent quand tu frappes une créature."),
    "gui.wayfarers.settings.quest_tracker": ("Quest tracker", "Suivi de quête"),
    "gui.wayfarers.settings.quest_tracker.tip": ("The tracked quest in the top-right corner (pick it in the journal).",
                                                 "La quête suivie en haut à droite (à choisir dans le journal)."),
    "gui.wayfarers.settings.tips": ("Tip cards", "Cartes d'astuce"),
    "gui.wayfarers.settings.tips.tip": ("One-time tips the first time you meet a system.",
                                        "Astuces affichées une fois, la première fois que tu découvres un système."),
    "gui.wayfarers.settings.keys": ("Keys", "Touches"),
    "gui.wayfarers.settings.keys.tip": ("Journal, talents, active talent, magnet, sorting, wand symmetry, manual page.",
                                        "Journal, talents, talent actif, aimant, tri, symétrie de la baguette, page du manuel."),
    "gui.wayfarers.settings.keys.button": ("Key bindings...", "Modifier..."),
    "key.wayfarers.manual_page": ("Manual page of the hovered item (hold)", "Page du manuel de l'objet survolé (maintenir)"),
    "gui.wayfarers.quests.keys": ("Arrows: quests and chapters - Enter: track", "Flèches : quêtes et chapitres - Entrée : suivre"),
    "gui.wayfarers.tip.title": ("Tip", "Astuce"),
    "gui.wayfarers.storage.sort": ("Sort this container (or middle-click)", "Trier ce conteneur (ou clic molette)"),
    "gui.wayfarers.storage.sort_inventory": ("Sort your inventory (R)", "Trier ton inventaire (R)"),
    "gui.wayfarers.storage.take_all": ("Take everything", "Tout prendre"),
    "gui.wayfarers.storage.deposit": ("Deposit the items this container already holds",
                                      "Déposer les objets que ce conteneur contient déjà"),
    "gui.wayfarers.storage.nearby": ("Quick-stack into chests within 8 blocks that already hold those items",
                                     "Ranger dans les coffres à 8 blocs qui contiennent déjà ces objets"),
    "gui.wayfarers.storage.search": ("Search...", "Rechercher..."),
    "message.wayfarers.wand.undone": ("Undone: %s blocks back in your inventory", "Annulé : %s blocs rendus"),
    "message.wayfarers.wand.nothing": ("Nothing to undo", "Rien à annuler"),
    "message.wayfarers.wand.symmetry": ("Symmetry: %s", "Symétrie : %s"),
    "message.wayfarers.wand.symmetry_at": ("Symmetry: %s - centre %s %s %s", "Symétrie : %s - centre %s %s %s"),
    "message.wayfarers.wand.centre": ("Mirror centre set at %s %s %s - symmetry: %s (G or sneak-use it again to change)",
                                      "Centre du miroir placé en %s %s %s - symétrie : %s (G ou accroupi dessus pour changer)"),
    "message.wayfarers.wand.placed_mirrored": ("Placed %s blocks + %s mirrored", "%s blocs posés + %s en miroir"),
    "message.wayfarers.wand.symmetry.off": ("off", "désactivée"),
    "message.wayfarers.wand.symmetry.x": ("mirror X (east/west)", "miroir X (est/ouest)"),
    "message.wayfarers.wand.symmetry.z": ("mirror Z (north/south)", "miroir Z (nord/sud)"),
    "message.wayfarers.wand.symmetry.xz": ("mirror X + Z (4 ways)", "miroir X + Z (4 côtés)"),
    "tooltip.wayfarers.wand.symmetry": ("Symmetry: %s", "Symétrie : %s"),
    "tooltip.wayfarers.wand.symmetry_at": ("Symmetry: %s, centre %s %s %s", "Symétrie : %s, centre %s %s %s"),
    "key.wayfarers.wand_symmetry": ("Builder's Wand: symmetry mode", "Baguette du bâtisseur : mode symétrie"),
    "message.wayfarers.chisel.variant": ("%s (%s/%s)", "%s (%s/%s)"),
    "message.wayfarers.chisel.none": ("The chisel can't carve %s", "Le burin ne sait pas tailler : %s"),
    "gui.wayfarers.chisel_table.empty": ("Put a stack of blocks in the slot", "Pose une pile de blocs dans la case"),
    "gui.wayfarers.chisel_table.none": ("No variants for this item", "Aucune variante pour cet objet"),
    "gui.wayfarers.chisel_table.pick": ("%s variants - click one to convert the stack", "%s variantes - clique pour transformer la pile"),
    "gui.wayfarers.terminal.sort.count": ("Count", "Qté"),
    "gui.wayfarers.terminal.sort.name": ("Name", "Nom"),
    "gui.wayfarers.terminal.sort.mod": ("Mod", "Mod"),
    "gui.wayfarers.terminal.sort.tip": ("Sort: by count, by name or by mod. Search @name to filter by mod.",
                                        "Tri : par quantité, par nom ou par mod. Cherche @nom pour filtrer par mod."),
    "gui.wayfarers.terminal.network.tip": ("Network: the linked containers (exclude one, show them in the world)",
                                           "Réseau : les conteneurs reliés (en exclure un, les montrer dans le monde)"),
    "gui.wayfarers.terminal.network": ("Linked containers", "Conteneurs reliés"),
    "gui.wayfarers.terminal.show": ("Show in world", "Montrer"),
    "gui.wayfarers.terminal.show.tip": ("Outline every linked container for 10 seconds (gold: linked, red: excluded)",
                                        "Encadre chaque conteneur relié pendant 10 secondes (or : relié, rouge : exclu)"),
    "gui.wayfarers.terminal.back": ("Items", "Objets"),
    "gui.wayfarers.terminal.group": ("%s x%s", "%s x%s"),
    "gui.wayfarers.terminal.double": ("%s (double)", "%s (double)"),
    # status lines: under the grid, 172 px wide (with real numbers) in both languages
    "gui.wayfarers.terminal.status": ("%s chests - %s free slots", "%s coffres - %s cases libres"),
    "gui.wayfarers.terminal.network_status": ("%s linked, %s relays, reach %s", "%s reliés, %s relais, portée %s"),
    "gui.wayfarers.terminal.capped": ("Too many containers: the server's limit (storage.maxContainers) is reached.",
                                      "Trop de conteneurs : la limite du serveur (storage.maxContainers) est atteinte."),
    "gui.wayfarers.terminal.stored": ("In storage: %s", "En stock : %s"),
    "gui.wayfarers.terminal.all_empty": ("The linked chests are empty. Click here with an item, or Store all.",
                                         "Les coffres reliés sont vides. Clique ici avec un objet, ou Tout ranger."),
    "gui.wayfarers.terminal.link.pos": ("X %s  Y %s  Z %s", "X %s  Y %s  Z %s"),
    "gui.wayfarers.terminal.link.slots": ("%s slots", "%s emplacements"),
    "gui.wayfarers.terminal.link.exclude": ("Click: exclude it (the terminal no longer takes or stores items there)",
                                            "Clic : l'exclure (le terminal n'y prend ni n'y range plus rien)"),
    "gui.wayfarers.terminal.link.include": ("Excluded. Click: link it again", "Exclu. Clic : le relier à nouveau"),
    "gui.wayfarers.terminal.store_all": ("Store all", "Tout ranger"),
    "gui.wayfarers.terminal.store_matching": ("Store matching", "Ranger identiques"),
    "gui.wayfarers.terminal.empty": ("No chest within %s blocks. Put the terminal in your base, or add Storage Relays near your chests.",
                                     "Aucun coffre à %s blocs. Pose le terminal dans ta base, ou ajoute des relais de stockage près des coffres."),
    "message.wayfarers.quick_stack": ("Stored %s items into %s chests", "%s objets rangés dans %s coffres"),
    "gui.wayfarers.quests.track": ("Track", "Suivre"),
    "gui.wayfarers.quests.untrack": ("Stop tracking", "Ne plus suivre"),
    "gui.wayfarers.quests.tracker": ("Tracked quest", "Quête suivie"),
    "gui.wayfarers.quests.objectives": ("Objectives: %s / %s", "Objectifs : %s / %s"),
    "gui.wayfarers.quests.rewards": ("Rewards", "Récompenses"),
    "gui.wayfarers.quests.done": ("Completed!", "Terminée !"),
    "gui.wayfarers.quests.hidden": ("Secret quest", "Quête secrète"),
    "gui.wayfarers.quests.locked": ("Complete first: %s", "Termine d'abord : %s"),
    "message.wayfarers.welcome": ("Welcome, wayfarer! Your Atlas tracks the guild's journey — press [%s] to see every quest.",
                                  "Bienvenue, voyageur ! Ton Atlas suit le voyage de la guilde — appuie sur [%s] pour voir toutes les quêtes."),
    "message.wayfarers.shared": ("%s completed \"%s\" for the whole guild!", "%s a accompli « %s » pour toute la guilde !"),
    "message.wayfarers.atlas.header": ("== Guild journey ==", "== Voyage de la guilde =="),
    "message.wayfarers.atlas.chapter": ("%s: %s/%s", "%s : %s/%s"),
    "message.wayfarers.atlas.next": ("Next goal: %s", "Prochain objectif : %s"),
    "message.wayfarers.atlas.done": ("Every chapter is complete. Legendary!", "Tous les chapitres sont terminés. Légendaire !"),
    "message.wayfarers.compass.target": ("Compass target: %s", "Cible de la boussole : %s"),
    "message.wayfarers.compass.found": ("%s: %s blocks %s (x %s, z %s)", "%s : %s blocs vers %s (x %s, z %s)"),
    "message.wayfarers.compass.none": ("No %s nearby in this dimension.", "Aucun(e) %s à proximité dans cette dimension."),
    "message.wayfarers.compass.any": ("any structure", "n'importe quelle structure"),
    "message.wayfarers.waystone.discovered": ("Waystone discovered: %s (shared with everyone)",
                                              "Pierre de voyage découverte : %s (partagée avec tout le monde)"),
    "message.wayfarers.waystone.list": ("Waystones — click to travel:", "Pierres de voyage — clique pour voyager :"),
    "message.wayfarers.waystone.entry": ("[%s] %s (%s)", "[%s] %s (%s)"),
    "message.wayfarers.waystone.none": ("No other waystone discovered yet.", "Aucune autre pierre découverte pour l'instant."),
    "message.wayfarers.waystone.travel": ("Whoosh! Welcome to %s.", "Fiouuu ! Bienvenue à %s."),
    "message.wayfarers.waystone.unknown": ("That waystone no longer exists.", "Cette pierre de voyage n'existe plus."),
    "message.wayfarers.waystone.hover": ("Click to travel", "Clique pour voyager"),
    "message.wayfarers.waystone.too_far": ("Stand next to a waystone to use it.",
                                           "Tiens-toi près d'une pierre de voyage pour l'utiliser."),
    "message.wayfarers.waystone.gone": ("That waystone was destroyed.", "Cette pierre de voyage a été détruite."),
    "gui.wayfarers.waystones.title": ("Waystones", "Pierres de voyage"),
    "gui.wayfarers.waystones.search": ("Search...", "Rechercher..."),
    "gui.wayfarers.waystones.travel": ("Travel", "Voyager"),
    "gui.wayfarers.waystones.pin": ("Pin", "Épingler"),
    "gui.wayfarers.waystones.unpin": ("Unpin", "Désépingler"),
    "gui.wayfarers.waystones.rename": ("Rename", "Renommer"),
    "gui.wayfarers.waystones.save": ("Save", "Valider"),
    "gui.wayfarers.waystones.here": ("you are here", "vous êtes ici"),
    "gui.wayfarers.waystones.empty": ("Discover other waystones to travel between them. Every waystone found by "
                                      "anyone in the group appears here.",
                                      "Découvre d'autres pierres pour voyager entre elles. Toute pierre trouvée par "
                                      "un membre du groupe apparaît ici."),
    "gui.wayfarers.waystones.distance": ("%s m away", "à %s m"),
    "gui.wayfarers.waystones.coords": ("X %s  Y %s  Z %s", "X %s  Y %s  Z %s"),
    "gui.wayfarers.waystones.hint": ("Enter or double-click: travel - star: pin",
                                     "Entrée ou double-clic : voyager - étoile : épingler"),
    "gui.wayfarers.dim.overworld": ("Overworld", "Surface"),
    "gui.wayfarers.dim.the_nether": ("Nether", "Nether"),
    "gui.wayfarers.dim.the_end": ("The End", "L'End"),
    "message.wayfarers.terminal.deposit": ("Stored %s items in %s chests.", "%s objets rangés dans %s coffres."),
    "message.wayfarers.terminal.sorted": ("Sorted %s chests.", "%s coffres triés."),
    "message.wayfarers.terminal.nothing": ("No chest within %s blocks.", "Aucun coffre à moins de %s blocs."),
    "message.wayfarers.terminal.showing": ("%s linked containers outlined for %s s", "%s conteneurs reliés encadrés pendant %s s"),
    "message.wayfarers.relay.linked": ("Relay linked to the Guild Terminal at %s %s %s",
                                       "Relais relié au terminal de guilde en %s %s %s"),
    "message.wayfarers.relay.unlinked": ("Not linked: place it within %s blocks of a Guild Terminal or %s blocks of a linked relay.",
                                         "Non relié : pose-le à %s blocs d'un terminal de guilde ou à %s blocs d'un relais relié."),
    "message.wayfarers.grave": ("Your belongings rest in a grave at %s %s %s (%s).",
                                "Tes affaires reposent dans une tombe en %s %s %s (%s)."),
    "message.wayfarers.grave.restored": ("Belongings recovered.", "Affaires récupérées."),
    "message.wayfarers.magnet.on": ("Magnet on", "Aimant activé"),
    "message.wayfarers.magnet.off": ("Magnet off", "Aimant désactivé"),
    "message.wayfarers.recall": ("Recalled home.", "Retour à la maison."),
    "message.wayfarers.sorted": ("Inventory sorted.", "Inventaire trié."),
    "message.wayfarers.altar.need": ("The altar needs %s.", "L'autel réclame : %s."),
    "message.wayfarers.altar.busy": ("A guardian is already awake nearby.", "Un gardien est déjà réveillé tout près."),
    "message.wayfarers.ability.no_target": ("Nothing in reach.", "Rien à portée."),
    "message.wayfarers.skill.nothing_to_forget": ("You have no talent to forget.", "Tu n'as aucun talent à oublier."),
    "message.wayfarers.altar.awake": ("%s awakens!", "%s se réveille !"),
    "message.wayfarers.boss.defeated": ("%s has been defeated! The sealed bars crumble.",
                                        "%s est vaincu ! Les barreaux scellés s'effondrent."),
    "message.wayfarers.brass_golem.built": ("Gears whir, steam hisses: your Brass Golem wakes up! It follows you and "
                                            "fights monsters. Sneak-use it with an empty hand: guard here / follow. "
                                            "Brass ingots repair it.",
                                            "Les engrenages ronronnent, la vapeur siffle : ton golem de laiton se réveille ! "
                                            "Il te suit et combat les monstres. Accroupi + clic droit main vide : garder ici / "
                                            "suivre. Les lingots de laiton le réparent."),
    "message.wayfarers.brass_golem.guard": ("Brass Golem: guarding this spot.", "Golem de laiton : il garde cet endroit."),
    "message.wayfarers.brass_golem.follow": ("Brass Golem: following you.", "Golem de laiton : il te suit."),
    "message.wayfarers.brass_golem.need": ("A Brass Golem needs two Blocks of Brass stacked on top of each other.",
                                           "Un golem de laiton demande deux blocs de laiton empilés l'un sur l'autre."),
    "message.wayfarers.brass_golem.room": ("No room for a Brass Golem here: it needs a little space around and above "
                                           "the two blocks.",
                                           "Pas assez de place pour un golem de laiton : il lui faut un peu d'espace autour "
                                           "et au-dessus des deux blocs."),
    "message.wayfarers.void_saved": ("The void spits you back out.", "Le vide te recrache."),
    "message.wayfarers.cooldown": ("Recharging...", "Recharge..."),
    "message.wayfarers.kit": ("Kit '%s' given.", "Kit « %s » donné."),
    "message.wayfarers.progress.reset": ("Wayfarers progression reset.", "Progression Wayfarers réinitialisée."),
    "message.wayfarers.progress.complete": ("Every Wayfarers quest granted.", "Toutes les quêtes Wayfarers accordées."),
    "message.wayfarers.locate": ("%s is at %s, %s (%s blocks).", "%s se trouve en %s, %s (%s blocs)."),
    "chapter.wayfarers.first_steps": ("I. First Steps", "I. Premiers pas"),
    "chapter.wayfarers.explorer": ("II. Overworld Explorer", "II. Explorateur de la Surface"),
    "chapter.wayfarers.depths": ("III. The Depths", "III. Les profondeurs"),
    "chapter.wayfarers.nether": ("IV. The Nether", "IV. Le Nether"),
    "chapter.wayfarers.end": ("V. The End", "V. L'End"),
    "message.wayfarers.elite": ("Elite %s", "%s d'élite"),
    "title.wayfarers.enemy_felled": ("ENEMY FELLED", "ENNEMI ABATTU"),
    "message.wayfarers.blood_moon.rise": ("The Blood Moon rises... monsters grow restless and strong. Stay together!",
                                          "La lune de sang se lève... les monstres deviennent enragés. Restez groupés !"),
    "message.wayfarers.blood_moon.end": ("Dawn breaks: the Blood Moon fades.", "L'aube se lève : la lune de sang s'efface."),
    "message.wayfarers.danger": ("Danger: %s", "Danger : %s"),
    "message.wayfarers.danger.0": ("Safe", "Sûr"),
    "message.wayfarers.danger.1": ("Low", "Faible"),
    "message.wayfarers.danger.2": ("Moderate", "Modéré"),
    "message.wayfarers.danger.3": ("High", "Élevé"),
    "message.wayfarers.danger.4": ("Severe", "Sévère"),
    "message.wayfarers.danger.5": ("Extreme", "Extrême"),
    "message.wayfarers.danger.6": ("Deadly", "Mortel"),
    "message.wayfarers.danger.7": ("Legendary", "Légendaire"),
    "tooltip.wayfarers.set_bonus": ("Full set bonus:", "Bonus d'ensemble complet :"),
    "tooltip.wayfarers.magnet.on": ("Active", "Actif"),
    "tooltip.wayfarers.magnet.off": ("Inactive", "Inactif"),
}


# boss remembrances and weapons (tools/wf/bossgear.py)
def _boss_gear():
    from .bossgear import BOSS_GEAR, remembrance_id
    for row in BOSS_GEAR:
        boss, tier, wid, (wen, wfr), (ten, tfr), (ren, rfr) = row[:6]
        ITEMS[remembrance_id(boss)] = (ren, rfr, "Craft it with four tier materials and two diamonds into its boss weapon.",
                                       "Avec quatre matériaux de palier et deux diamants, il devient l'arme du boss.")
        ITEMS[wid] = (wen, wfr, ten, tfr)


_boss_gear()


def _gadgets():
    from .gadgets import ENTITIES as GADGET_ENTITIES, register_content
    register_content(ITEMS)
    ENTITIES.update(GADGET_ENTITIES)


_gadgets()


def _ocean():
    from .ocean import register_content
    register_content(ITEMS, ENTITIES, SPAWN_EGGS)


_ocean()
