"""Hand-drawn 16x16 sprite shapes (ASCII) and palettes used by gen_textures.py.

Legend:  . transparent   o outline   a/b/c main material light/mid/dark
         h/H handle light/dark   g/G accent light/dark   w highlight
"""

SHAPES = {
    "sword": """
..............oo
.............oao
............oabo
...........oabo.
..........oabo..
.........oabo...
........oabo....
...o...oabo.....
...ooooabo......
....oggbo.......
....ogGo........
...ohHoggo......
..ohHo..oo......
.ohHo...........
ogGo............
oo..............""",
    "blade": """
...........ooo..
..........oaaao.
.........oabbco.
........oabbco..
.......oabbco...
......oabbco....
.....oabbco.....
..o.oabbco......
..ooabbco.......
...oggco........
...ogGo.........
..ohHooo........
.ohHo...........
ohHo............
oGo.............
oo..............""",
    "hammer": """
....oooooooo....
...oaaaaaaabo...
...oabbbbbbco...
...oabbbbbbco...
...obccccccco...
....oooohooo....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.oggo...........
oGGo............
oo..............
................""",
    "scythe": """
....ooooooo.....
..ooaaaaaabo....
.oabbbbbbbbco...
oabbccccccbbo...
oaco.oooo.ocbo..
oco.......ohco..
oo.......ohHo...
........ohHo....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..oggo..........
.oGGo...........
.oo.............""",
    "spear": """
.............ooo
............oaao
...........oabco
..........oabco.
.........oggco..
........ohgo....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
ohHo............
oHo.............
oo..............""",
    "staff": """
...........ooo..
..........ogwgo.
.........ogwggGo
.........oggGGo.
..........oGGo..
.........ohHo...
........ohHo....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.oaao...........
oaco............
oo..............""",
    "pickaxe": """
...ooooooo......
..oaaaaaabo.....
.oabbbbbbbco....
.oaco..oHbbco...
..oo..ohHocbo...
.....ohHo..oco..
....ohHo....oo..
...ohHo.........
..ohHo..........
.ohHo...........
ohHo............
oHo.............
oo..............
................
................
................""",
    "axe": """
......oooo......
.....oaaabo.....
....oabbbbco....
....oabbbbHo....
....oabbboHo....
.....occoHHo....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
ohHo............
oo..............
................""",
    "boomerang": """
................
.......ooo......
......oaabo.....
.....oabbbco....
....oabbcco.....
...oabbco.......
..oabbco........
.oabbco.........
.oabco..........
.oabbooooooo....
..oabbbbbbbbo...
...oaccccccbbo..
....oooooooocco.
............ooo.
................
................""",
    "shovel": """
.........ooo....
........oaabo...
.......oabbbco..
.......obbbbco..
.......obbbcco..
........occco...
.......oHoo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............
................""",
    "hoe": """
....oooooo......
...oaaaabbo.....
...obbbbbcco....
....ooooohHco...
........ohHoo...
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............
................
................""",
    "nugget": """
................
................
................
................
................
................
......ooo.......
.....oaabo......
....oabbbco.....
....obbbbco.....
.....occco......
......ooo.......
................
................
................
................""",
    "raw": """
................
................
................
.....oooo.......
....oaabbo......
...oabbgbbo.....
...obbbbbbco....
..oabgbbbbbco...
..obbbbbbgbco...
..obbbbbbbcco...
...occbbbccco...
....ooccccoo....
......oooo......
................
................
................""",
    "cloth": """
................
................
..oooooooooooo..
..oaaaaaaaaabo..
..oabbgbbbgbbo..
..obbbbbbbbbbo..
..obgbbbgbbbco..
..obbbbbbbbbco..
..obbbgbbbgbco..
..obbbbbbbbbco..
..occcccccccco..
...ooooooooooo..
................
................
................
................""",
    "staff_flame": """
..........g.....
.........gGg....
........gGGgg...
........gGwGg...
.........gGg....
........ohHo....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............
................""",
    "staff_snow": """
.........g.g.g..
..........ggg...
........gggwggg.
..........ggg...
.........g.g.g..
........ohHo....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............
................""",
    "staff_bolt": """
...........gg...
..........gg....
.........gwgg...
...........gg...
..........gg....
........ohg.....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............
................""",
    "staff_cross": """
..........gg....
..........gg....
........ggwwgg..
........ggwwgg..
..........gg....
........ohgg....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............
................""",
    "wand_ring": """
.........ggg....
........g...g...
........g.w.g...
........g...g...
.........ggg....
........ohH.....
.......ohHo.....
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..oHo...........
..o.............
................
................
................""",
    "cane": """
.......oooo.....
......oaabbo....
.....oa.oobco...
.....ob.o..co...
......oo.ohHo...
.........ohHo...
........ohHo....
.......ohHo.....
......ohHo......
.....ohHo.......
....ogHo........
...oGgo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............""",
    "vial": """
................
.......oo.......
......oaao......
.......oo.......
......oaao......
.....oawbbo.....
....oagggGbo....
...oagggggGco...
...ogggwgggGo...
...oggggggGGo...
...oGgggggGGo...
....oGGgGGGo....
.....oooooo.....
................
................
................""",
    "amulet": """
..oo.......oo...
...oo.....oo....
....oo...oo.....
.....oo.oo......
......ooo.......
.....oaabo......
....oagggbo.....
....ogwggGo.....
....oggggGo.....
.....oGGGo......
......ooo.......
................
................
................
................
................""",
    "trident": """
....o..o..o.....
....a..a..a.....
....ab.ab.ab....
....obbbbbbo....
......obbo......
.......ho.......
......ohHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............
................
................""",
    "mace": """
......o.o.o.....
.....oaabbbo....
....oabgbbbco...
....oabbbbgco...
....obgbbbbco...
.....obbbcco....
......oHHo......
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............
................
................""",
    "lance": """
..............oa
.............oab
............oabo
...........oabo.
..........oabo..
.........oabo...
........oabo....
.......ogggo....
......ohHgo.....
.....ohHo.......
....ohHo........
...ohHo.........
..ohHo..........
.ohHo...........
.oHo............
..o.............""",
    "fist": """
................
....oooooo......
...oabbbbbo.....
...oabcbcbco....
...oabbbbbbo....
...oaabbbbco....
...oabbbbbco....
...obbbbbbco....
....obgggco.....
....obbbbco.....
....occcco......
.....oooo.......
................
................
................
................""",
    "horn": """
................
...........ooo..
..........oaabo.
.........oabbco.
........oabbco..
.......oabbco...
......oabbco....
.....oabbco.....
....oabgco......
...oabgco.......
..oaggco........
..oGgco.........
...ooo..........
................
................
................""",
    "greatsword": """
.............ooo
............oaao
...........oabbo
..........oabbo.
.........oabbo..
........oabbo...
.......oabbo....
......oabbo.....
.oo..oabbo......
.ogooabbo.......
..oggbbo........
...oggo.........
...oHgGo........
..oHHo.oo.......
.oHHo...........
.oo.............""",
    "ingot": """
................
................
................
................
................
.....ooooooo....
....oaaaaaabo...
...oabbbbbbbco..
..oabbbbbbbbco..
.oaaaaaaaabbco..
.obbbbbbbbbco...
.occcccccccco...
..oooooooooo....
................
................
................""",
    "shard": """
................
.........oo.....
........oaao....
.......oawbo....
......oawbbo....
.....oawbbco....
....oaabbcco....
....oabbbcco....
...oabbbcco.....
...oabbcco......
..oabbccoo......
..oabcco........
..obcco.........
...oco..........
....o...........
................""",
    "gem": """
................
................
.....oooooo.....
....oawaaabo....
...oawbbbbbco...
..oaabbbbbbbco..
..obbbbbbbbbco..
...obbbbbbbco...
....obbbbbco....
.....obbbco.....
......obco......
.......oo.......
................
................
................
................""",
    "fragment": """
................
..oooooooo......
..owaaaaabo.....
..oabgbbbbo.....
..oabgGbbbbo....
..oabbgbbbbo....
..oabbbgbbbo....
..oabbbgGbbbo...
..oabbbbgbbbo...
..oabbbbbggbo...
..oabbbbbbbbo...
..occcccccbbo...
...oooooocco....
.........oo.....
................
................""",
    "ember": """
................
.......o........
......ogo.......
......ogo..o....
.....ogwgoogo...
....ogwwggggo...
...ogwwaaggGo...
...ogwaabbgGo...
..ogaabbbbbGo...
..ogabbccbbGo...
..oGabcccbbGo...
...oGbbccbGo....
....oGGbbGo.....
.....ooooo......
................
................""",
    "heart": """
................
................
...ooo....ooo...
..oaaao..oaabo..
.oawwaaooaabbco.
.oawaaaaaabbbco.
.oaaaaaaaabbbco.
.oaaaaaaabbbcco.
..oaaaaabbbcco..
...oaaabbbcco...
....oaabbcco....
.....oabcco.....
......occo......
.......oo.......
................
................""",
    "scale": """
................
......oooo......
....ooaaaboo....
...oawaaabbbo...
..oawaaabbbbco..
..oaaaabbbbbco..
.oaaaabbbbbbcco.
.obbbbbbbbbccco.
.obgggbbbgggcco.
.obbbbbbbbbccco.
..obbbbbbbbcco..
..occcbbbcccco..
...oocccccccoo..
.....oooooo.....
................
................""",
    "compass": """
................
.....oooooo.....
...ooaaaaaaoo...
..oaabbbbbbaao..
..oabbbwgbbbao..
.oabbbbwgbbbbao.
.oabbbbwGbbbbao.
.oabbbbhHbbbbao.
.oabbbbhHbbbbao.
.oabbbbhbbbbbao.
..oabbbbbbbbao..
..oaabbbbbbaao..
...ooccccccoo...
.....oooooo.....
................
................""",
    "ring": """
................
................
.......oo.......
......ogwo......
.....ogwGGo.....
.....oGGGGo.....
....ooaooaoo....
...oao....oao...
..oao......oao..
..obo......obo..
..obo......obo..
..oco......oco..
...oco....oco...
....oocoocoo....
......oooo......
................""",
    "backpack": """
................
.....oooooo.....
....oHHooHHo....
....oHo..oHo....
..oooooooooooo..
.oaaaaaaaaaaabo.
.oabbbbbbbbbbco.
.oabbgggggbbbco.
.oabbgGGGgbbbco.
.oabbgggggbbbco.
.oabbbbbbbbbbco.
.oabbbbbbbbbbco.
.oaccccccccccco.
..oooooooooooo..
................
................""",
    "book": """
................
..oooooooooooo..
..ogaaaaaaaaabo.
..ogabbbbbbbbbo.
..ogabbwwwbbbbo.
..ogabwgggwbbbo.
..ogabwgGgwbbbo.
..ogabbwwwbbbbo.
..ogabbbbbbbbbo.
..ogabbbbbbbbbo.
..ogabbbbbbbbbo.
..ogaccccccccco.
..oghhhhhhhhhho.
..ooHHHHHHHHHHo.
...oooooooooooo.
................""",
    "scroll": """
................
...oooooooooo...
..ohhhhhhhhhhho.
..oHhaaaaaaaaHo.
...ohabbbbbbao..
...ohabgggbbao..
...ohabbbbbbao..
...ohabggbbbao..
...ohabbbbbbao..
...ohabgggbbao..
...ohabbbbbbao..
..ohhaaaaaaaahho
..oHHHHHHHHHHHo.
...ooooooooooo..
................
................""",
    "helmet": """
................
................
................
....oooooooo....
...oaaaaaaabo...
..oabbbbbbbbco..
..oabggggggbco..
..oabgoooogbco..
..oabo....obco..
..oaco....occo..
..ooo......ooo..
................
................
................
................
................""",
    "chestplate": """
................
..oooo....oooo..
.oaabo....oabco.
.oabbooooooobco.
.oabbbbbbbbbbco.
..ooabbggbbcoo..
....oabggbco....
....oabbbbco....
....oabbbbco....
....oabbbbco....
....oabbbbco....
....occcccco....
.....oooooo.....
................
................
................""",
    "leggings": """
................
...oooooooooo...
...oaaaaaaabo...
...oagggggGbo...
...oabbooabco...
...oabo..oabo...
...oabo..oabo...
...oabo..oabo...
...oabo..oabo...
...oabo..oabo...
...ocoo..ooco...
...ooo....ooo...
................
................
................
................""",
    "boots": """
................
................
................
................
................
...oooo..oooo...
...oabo..oabo...
...oabo..oabo...
...oabo..oabo...
..oabbo..oabbo..
.ogabbo..ogabbo.
.occcco..occcco.
.oooooo..oooooo.
................
................
................""",
    "egg": """
................
......oooo......
.....oaaabo.....
....oaggabbo....
....oagaabbo....
...oaaaaabbco...
...oaabggbbco...
...oaabggbbco...
..oaaaaaabbbco..
..oaggaabbbbco..
..oaggabbbbcco..
...oaaabbbccco..
...obbbbbccco...
....occcccco....
.....oooooo.....
................""",
    "gear": """
................
.......oo.......
...oo.oaao.oo...
..oaaooabooaao..
..oaaaabbbbbco..
...oaaoooobco...
.ooaaoo..oobcoo.
oaabbo....obbco.
oabbbo....obcco.
.oobbco..ocbcoo.
...obcooooccco..
..obbccbbcccco..
..occooccoocco..
...oo.occo.oo...
.......oo.......
................""",
    "clockwork_heart": """
................
................
...ooo....ooo...
..oaaao..oaabo..
.oawwaaooaabbco.
.oawaaagGabbbco.
.oaaaGgGgGbbbco.
.oaaagGoGgabcco.
..oaaGgGgGbcco..
...oaagGbbcco...
....oaabbcco....
.....oabcco.....
......occo......
.......oo.......
................
................""",
    "orb": """
................
................
.....oooooo.....
....owwaaabo....
...owwaaabbbo...
..owaaagabbbco..
..oaaaggGbbbco..
..oaaagGGbbbco..
..oaabbGbbbcco..
..oabbbbbbbcco..
...obbbbbccco...
....obbcccco....
.....oooooo.....
................
................
................""",
    # Engraver's Chisel: flat steel blade (top right), brass ferrule, wooden grip with a struck cap
    "chisel": """
.............o..
............owo.
...........oawwo
..........oaabwo
.........oaabco.
.........oabco..
.......ooacco...
......ogacoo....
.....oggGo......
....ohhGGo......
...ohhHoo.......
..ohhHo.........
.ohhHo..........
oggHo...........
ogGo............
.oo.............""",
}

# material palettes: (light, mid, dark, outline)
MATERIALS = {
    "iron": ((236, 236, 236), (198, 198, 198), (130, 130, 136), (45, 45, 52)),
    "cartographer": ((234, 214, 160), (196, 160, 98), (128, 96, 52), (52, 36, 18)),
    "lithite": ((150, 232, 214), (64, 178, 168), (28, 102, 108), (14, 40, 48)),
    "ember": ((255, 214, 120), (236, 120, 40), (156, 44, 22), (60, 14, 10)),
    "void": ((214, 168, 255), (146, 86, 210), (76, 34, 128), (28, 10, 52)),
    "frost": ((230, 250, 255), (150, 210, 245), (70, 130, 200), (20, 44, 80)),
    "storm": ((250, 250, 190), (190, 200, 230), (90, 100, 150), (30, 32, 60)),
    "light": ((255, 255, 230), (250, 228, 140), (200, 160, 60), (80, 56, 20)),
    "warden": ((120, 220, 200), (40, 140, 130), (20, 80, 82), (8, 30, 34)),
    "leather": ((196, 138, 84), (150, 98, 54), (100, 62, 32), (40, 24, 12)),
    "map": ((246, 236, 206), (222, 204, 160), (170, 146, 102), (70, 54, 30)),
    "gold": ((255, 246, 140), (240, 200, 50), (180, 120, 20), (70, 44, 6)),
    "brass": ((246, 214, 122), (200, 158, 70), (138, 100, 40), (58, 40, 16)),
    "copper": ((236, 164, 112), (190, 112, 60), (124, 66, 34), (52, 26, 14)),
}

HANDLES = {
    "wood": ((150, 110, 66), (96, 66, 36)),
    "dark": ((80, 60, 70), (40, 28, 36)),
    "bone": ((230, 226, 206), (170, 164, 140)),
    "gold": ((250, 210, 70), (170, 120, 20)),
    "blaze": ((255, 200, 60), (200, 110, 20)),
    "purpur": ((200, 150, 210), (120, 80, 140)),
}

ACCENTS = {
    "gold": ((255, 230, 90), (190, 140, 20)),
    "emerald": ((120, 250, 160), (30, 160, 80)),
    "ruby": ((255, 110, 110), (170, 30, 40)),
    "sapphire": ((140, 190, 255), (40, 80, 200)),
    "amethyst": ((220, 170, 255), (130, 70, 200)),
    "ember": ((255, 220, 120), (240, 110, 30)),
    "ice": ((240, 255, 255), (140, 210, 250)),
    "red": ((235, 70, 60), (150, 30, 30)),
    "ink": ((90, 90, 120), (40, 40, 70)),
    "aether": ((200, 248, 255), (60, 200, 240)),
}
