#!/usr/bin/env python3
"""Generate Java constants shared with the data generators (structure catalog + quest chapters)."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wf import defs  # noqa: E402
import wf.structures  # noqa: E402,F401

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedContent.java")
QUESTS = os.path.join(ROOT, "src", "main", "resources", "data", "wayfarers", "quests.json")


def decor_java():
    from wf import decor
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "ModDecor.java")
    L = [
        "package com.wayfarers.generated;",
        "",
        "import com.wayfarers.registry.ModBlocks;",
        "import com.wayfarers.registry.ModItems;",
        "import net.minecraft.world.item.BlockItem;",
        "import net.minecraft.world.item.Item;",
        "import net.minecraft.world.level.block.Block;",
        "import net.minecraft.world.level.block.RotatedPillarBlock;",
        "import net.minecraft.world.level.block.SlabBlock;",
        "import net.minecraft.world.level.block.SoundType;",
        "import net.minecraft.world.level.block.StairBlock;",
        "import net.minecraft.world.level.block.WallBlock;",
        "import net.minecraft.world.level.block.state.BlockBehaviour;",
        "import net.minecraft.world.level.material.MapColor;",
        "import net.minecraftforge.registries.RegistryObject;",
        "",
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.function.Supplier;",
        "",
        "/** GENERATED by tools/gen_java.py from tools/wf/decor.py — do not edit by hand. */",
        "public final class ModDecor {",
        "    public static final List<RegistryObject<Item>> ITEMS = new ArrayList<>();",
        "",
    ]
    for bid, d in decor.DECOR.items():
        const = bid.upper()
        L.append(f'    public static final RegistryObject<Block> {const} = {"pillar" if d.get("pillar") else "block"}('
                 f'"{bid}", MapColor.{d["color"]}, SoundType.{d["sound"]}, {d["strength"]}F, {d.get("light", 0)}, '
                 f'{str(d.get("tool", "pickaxe") == "pickaxe").lower()});')
        for v in d["variants"]:
            vid = decor.variant_id(bid, v)
            L.append(f'    public static final RegistryObject<Block> {vid.upper()} = {v}("{vid}", {const});')
    L += [
        "",
        "    /** Forces class initialisation so every block/item is queued on the deferred registers. */",
        "    public static void init() {}",
        "",
        "    private static BlockBehaviour.Properties props(String name, MapColor color, SoundType sound, float strength, int light,",
        "                                                   boolean needsPickaxe) {",
        "        BlockBehaviour.Properties p = BlockBehaviour.Properties.of().mapColor(color).sound(sound).strength(strength, 6.0F)",
        "                .lightLevel(s -> light).setId(ModBlocks.BLOCKS.key(name));",
        "        return needsPickaxe ? p.requiresCorrectToolForDrops() : p;",
        "    }",
        "",
        "    private static RegistryObject<Block> block(String name, MapColor color, SoundType sound, float strength, int light,",
        "                                              boolean needsPickaxe) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new Block(props(name, color, sound, strength, light, needsPickaxe))));",
        "    }",
        "",
        "    /** A column that turns with the face it is placed on, like a log or a quartz pillar. */",
        "    private static RegistryObject<Block> pillar(String name, MapColor color, SoundType sound, float strength, int light,",
        "                                               boolean needsPickaxe) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new RotatedPillarBlock(",
        "                props(name, color, sound, strength, light, needsPickaxe))));",
        "    }",
        "",
        "    private static RegistryObject<Block> stairs(String name, Supplier<Block> base) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new StairBlock(base.get().defaultBlockState(),",
        "                BlockBehaviour.Properties.ofFullCopy(base.get()).setId(ModBlocks.BLOCKS.key(name)))));",
        "    }",
        "",
        "    private static RegistryObject<Block> slab(String name, Supplier<Block> base) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new SlabBlock(",
        "                BlockBehaviour.Properties.ofFullCopy(base.get()).setId(ModBlocks.BLOCKS.key(name)))));",
        "    }",
        "",
        "    private static RegistryObject<Block> wall(String name, Supplier<Block> base) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new WallBlock(",
        "                BlockBehaviour.Properties.ofFullCopy(base.get()).forceSolidOn().setId(ModBlocks.BLOCKS.key(name)))));",
        "    }",
        "",
        "    private static RegistryObject<Block> item(String name, RegistryObject<Block> block) {",
        "        ITEMS.add(ModItems.ITEMS.register(name, () -> new BlockItem(block.get(),",
        "                new Item.Properties().setId(ModItems.ITEMS.key(name)).useBlockDescriptionPrefix())));",
        "        return block;",
        "    }",
        "",
        "    private ModDecor() {}",
        "}",
        "",
    ]
    with open(out, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {os.path.relpath(out, ROOT)}")


def boss_gear_java():
    from wf.bossgear import BOSS_GEAR, remembrance_id
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "BossGear.java")
    flag_bits = {"fire": "FIRE", "slow": "SLOW", "weak": "WEAK", "blind": "BLIND", "poison": "POISON",
                 "lift": "LIFT", "lifesteal": "LIFESTEAL"}
    L = [
        "package com.wayfarers.generated;",
        "",
        "import com.wayfarers.item.BossWeaponItem;",
        "import com.wayfarers.item.TooltipItem;",
        "import com.wayfarers.registry.ModItems;",
        "import com.wayfarers.registry.ModMaterials;",
        "import net.minecraft.core.particles.ParticleOptions;",
        "import net.minecraft.core.particles.ParticleTypes;",
        "import net.minecraft.world.item.Item;",
        "import net.minecraft.world.item.Rarity;",
        "import net.minecraftforge.registries.RegistryObject;",
        "",
        "import java.util.function.Supplier;",
        "import java.util.function.UnaryOperator;",
        "",
        "/** GENERATED by tools/gen_java.py from tools/wf/bossgear.py: boss remembrances and boss weapons. */",
        "public final class BossGear {",
    ]
    for row in BOSS_GEAR:
        boss, tier, wid, wname, tip, rname, melee, ability, power, size, cd, particle, flags = row[:13]
        rid = remembrance_id(boss)
        L.append(f'    public static final RegistryObject<Item> {rid.upper()} = remembrance("{rid}");')
        props = "p -> p.durability(600).rarity(Rarity.EPIC)" if melee is None else \
            f"p -> p.sword(ModMaterials.{melee[0]}, {melee[1]}F, {melee[2]}F).rarity(Rarity.EPIC)"
        if tier in ("nether", "end"):
            props = props.replace(".rarity(Rarity.EPIC)", ".rarity(Rarity.EPIC).fireResistant()")
        bits = " | ".join(f"BossWeaponItem.{flag_bits[f]}" for f in flags.split(",") if f) or "0"
        L.append(f'    public static final RegistryObject<Item> {wid.upper()} = weapon("{wid}", {props},')
        L.append(f'            BossWeaponItem.Ability.{ability}, {power}F, {size}F, {cd}, () -> ParticleTypes.{particle}, {bits});')
    L += [
        "",
        "    private BossGear() {}",
        "",
        "    /** Loads the class so the items are registered. */",
        "    public static void init() {}",
        "",
        "    private static RegistryObject<Item> remembrance(String name) {",
        "        RegistryObject<Item> obj = ModItems.ITEMS.register(name, () -> new TooltipItem(new Item.Properties()",
        "                .setId(ModItems.ITEMS.key(name)).stacksTo(1).rarity(Rarity.EPIC).fireResistant()));",
        "        ModItems.ALL.add(obj);",
        "        return obj;",
        "    }",
        "",
        "    private static RegistryObject<Item> weapon(String name, UnaryOperator<Item.Properties> props,",
        "                                               BossWeaponItem.Ability ability, float power, float size, int cooldown,",
        "                                               Supplier<ParticleOptions> particle, int flags) {",
        "        RegistryObject<Item> obj = ModItems.ITEMS.register(name, () -> new BossWeaponItem(",
        "                props.apply(new Item.Properties().setId(ModItems.ITEMS.key(name))), ability, power, size, cooldown,",
        "                particle.get(), flags));",
        "        ModItems.ALL.add(obj);",
        "        return obj;",
        "    }",
        "}",
        "",
    ]
    with open(out, "w") as f:
        f.write("\n".join(L))
    print("wrote", out)


def guide_java():
    """GeneratedGuide.java: the manual's categories, pages (paragraph count, icon, related items) and tips."""
    from wf import guide
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedGuide.java")
    L = ["package com.wayfarers.generated;", "", "import java.util.List;", "",
         "/** GENERATED by tools/gen_java.py from tools/wf/guide.py — do not edit by hand. */",
         "public final class GeneratedGuide {",
         "    public record Category(String id, String icon) {}",
         "    public record Page(String id, String category, String icon, int paragraphs, List<String> items) {}",
         "    public record Tip(String id, String icon, String page) {}", "",
         "    public static final List<Category> CATEGORIES = List.of("]
    L.append(",\n".join(f'            new Category("{c}", "{i}")' for c, i, _ in guide.CATEGORIES))
    L += ["    );", "", "    public static final List<Page> PAGES = List.of("]
    pages = []
    for pid, cat, icon, _t, paras, items in guide.PAGES:
        its = ", ".join(f'"{i}"' for i in items)
        pages.append(f'            new Page("{pid}", "{cat}", "{icon}", {len(paras)}, List.of({its}))')
    L.append(",\n".join(pages))
    L += ["    );", "", "    public static final List<Tip> TIPS = List.of("]
    L.append(",\n".join(f'            new Tip("{t}", "{i}", "{pg}")' for t, i, _x, pg in guide.TIPS))
    L += ["    );", "", "    private GeneratedGuide() {}", "}", ""]
    with open(out, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {os.path.relpath(out, ROOT)}")


def skills_java():
    from wf import skills
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedSkills.java")
    with open(out, "w") as f:
        f.write(skills.java())
    print(f"wrote {os.path.relpath(out, ROOT)}")


def metals_java():
    from wf import metals
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedMetals.java")
    with open(out, "w") as f:
        f.write(metals.java())
    print(f"wrote {os.path.relpath(out, ROOT)}")


def machines_java():
    from wf import machines
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedMachines.java")
    with open(out, "w") as f:
        f.write(machines.java())
    print(f"wrote {os.path.relpath(out, ROOT)}")


def furniture_java():
    from wf import furniture
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedFurniture.java")
    with open(out, "w") as f:
        f.write(furniture.java())
    print(f"wrote {os.path.relpath(out, ROOT)}")


def worldblocks_java():
    from wf import worldblocks
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedWorldBlocks.java")
    with open(out, "w") as f:
        f.write(worldblocks.java())
    print(f"wrote {os.path.relpath(out, ROOT)}")


def main():
    guide_java()
    worldblocks_java()
    metals_java()
    machines_java()
    furniture_java()
    skills_java()
    decor_java()
    boss_gear_java()
    from wf import npcs
    npc_out = os.path.join(os.path.dirname(OUT), "GeneratedNpcs.java")
    with open(npc_out, "w") as f:
        f.write(npcs.java())
    print(f"wrote {os.path.relpath(npc_out, ROOT)}")
    chapters = json.load(open(QUESTS))
    lines = [
        "package com.wayfarers.generated;",
        "",
        "import java.util.List;",
        "",
        "/** GENERATED by tools/gen_java.py — do not edit by hand. */",
        "public final class GeneratedContent {",
        "    public record StructureInfo(String id, String dimension) {}",
        "",
        "    public record Chapter(String id, List<String> quests) {}",
        "",
        "    public static final List<StructureInfo> STRUCTURES = List.of(",
    ]
    entries = [f'            new StructureInfo("{s.id}", "{s.dimension}")' for s in defs.STRUCTURES]
    lines.append(",\n".join(entries))
    lines += ["    );", "", "    public static final List<Chapter> CHAPTERS = List.of("]
    ch = []
    for cid, quests in chapters.items():
        qs = ", ".join(f'"{q}"' for q in quests)
        ch.append(f'            new Chapter("{cid}", List.of({qs}))')
    lines.append(",\n".join(ch))
    lines += ["    );", ""]
    info_path = os.path.join(ROOT, "build", "quest_info.json")
    info = json.load(open(info_path)) if os.path.exists(info_path) else {}
    lines.append("    /** Quest rewards shown in the journal: \"xp|item*count;item*count\". */")
    lines.append("    public static final java.util.Map<String, String> REWARDS = java.util.Map.ofEntries(")
    ents = []
    for q, v in sorted(info.items()):
        items = ";".join(f"{i}*{c}" for i, c in v["items"])
        ents.append(f'            java.util.Map.entry("{q}", "{v["xp"]}|{items}")')
    lines.append(",\n".join(ents))
    lines += ["    );", "", "    private GeneratedContent() {}", "}", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
