#!/usr/bin/env python3
"""Generate Java constants shared with the data generators (structure catalog + quest chapters)."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wf import defs  # noqa: E402
import wf.structures  # noqa: E402,F401

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedContent.java")
QUESTS = os.path.join(ROOT, "src", "main", "resources", "data", "wayfarers", "quests.json")


def decor_java():
    from wf import decor
    out = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "ModDecor.java")
    L = [
        "package com.wayfarers.generated;",
        "",
        "import com.wayfarers.registry.ModBlocks;",
        "import com.wayfarers.registry.ModItems;",
        "import net.minecraft.world.item.BlockItem;",
        "import net.minecraft.world.item.Item;",
        "import net.minecraft.world.level.block.Block;",
        "import net.minecraft.world.level.block.SlabBlock;",
        "import net.minecraft.world.level.block.SoundType;",
        "import net.minecraft.world.level.block.StairBlock;",
        "import net.minecraft.world.level.block.WallBlock;",
        "import net.minecraft.world.level.block.state.BlockBehaviour;",
        "import net.minecraft.world.level.material.MapColor;",
        "import net.minecraftforge.registries.RegistryObject;",
        "",
        "import java.util.ArrayList;",
        "import java.util.List;",
        "import java.util.function.Supplier;",
        "",
        "/** GENERATED by tools/gen_java.py from tools/wf/decor.py — do not edit by hand. */",
        "public final class ModDecor {",
        "    public static final List<RegistryObject<Item>> ITEMS = new ArrayList<>();",
        "",
    ]
    for bid, d in decor.DECOR.items():
        const = bid.upper()
        L.append(f'    public static final RegistryObject<Block> {const} = block("{bid}", MapColor.{d["color"]}, '
                 f'SoundType.{d["sound"]}, {d["strength"]}F, {d.get("light", 0)});')
        for v in d["variants"]:
            vid = decor.variant_id(bid, v)
            L.append(f'    public static final RegistryObject<Block> {vid.upper()} = {v}("{vid}", {const});')
    L += [
        "",
        "    /** Forces class initialisation so every block/item is queued on the deferred registers. */",
        "    public static void init() {}",
        "",
        "    private static BlockBehaviour.Properties props(String name, MapColor color, SoundType sound, float strength, int light) {",
        "        return BlockBehaviour.Properties.of().mapColor(color).sound(sound).strength(strength, 6.0F)",
        "                .requiresCorrectToolForDrops().lightLevel(s -> light).setId(ModBlocks.BLOCKS.key(name));",
        "    }",
        "",
        "    private static RegistryObject<Block> block(String name, MapColor color, SoundType sound, float strength, int light) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new Block(props(name, color, sound, strength, light))));",
        "    }",
        "",
        "    private static RegistryObject<Block> stairs(String name, Supplier<Block> base) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new StairBlock(base.get().defaultBlockState(),",
        "                BlockBehaviour.Properties.ofFullCopy(base.get()).setId(ModBlocks.BLOCKS.key(name)))));",
        "    }",
        "",
        "    private static RegistryObject<Block> slab(String name, Supplier<Block> base) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new SlabBlock(",
        "                BlockBehaviour.Properties.ofFullCopy(base.get()).setId(ModBlocks.BLOCKS.key(name)))));",
        "    }",
        "",
        "    private static RegistryObject<Block> wall(String name, Supplier<Block> base) {",
        "        return item(name, ModBlocks.BLOCKS.register(name, () -> new WallBlock(",
        "                BlockBehaviour.Properties.ofFullCopy(base.get()).forceSolidOn().setId(ModBlocks.BLOCKS.key(name)))));",
        "    }",
        "",
        "    private static RegistryObject<Block> item(String name, RegistryObject<Block> block) {",
        "        ITEMS.add(ModItems.ITEMS.register(name, () -> new BlockItem(block.get(),",
        "                new Item.Properties().setId(ModItems.ITEMS.key(name)).useBlockDescriptionPrefix())));",
        "        return block;",
        "    }",
        "",
        "    private ModDecor() {}",
        "}",
        "",
    ]
    with open(out, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {os.path.relpath(out, ROOT)}")


def main():
    decor_java()
    chapters = json.load(open(QUESTS))
    lines = [
        "package com.wayfarers.generated;",
        "",
        "import java.util.List;",
        "",
        "/** GENERATED by tools/gen_java.py — do not edit by hand. */",
        "public final class GeneratedContent {",
        "    public record StructureInfo(String id, String dimension) {}",
        "",
        "    public record Chapter(String id, List<String> quests) {}",
        "",
        "    public static final List<StructureInfo> STRUCTURES = List.of(",
    ]
    entries = [f'            new StructureInfo("{s.id}", "{s.dimension}")' for s in defs.STRUCTURES]
    lines.append(",\n".join(entries))
    lines += ["    );", "", "    public static final List<Chapter> CHAPTERS = List.of("]
    ch = []
    for cid, quests in chapters.items():
        qs = ", ".join(f'"{q}"' for q in quests)
        ch.append(f'            new Chapter("{cid}", List.of({qs}))')
    lines.append(",\n".join(ch))
    lines += ["    );", "", "    private GeneratedContent() {}", "}", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
