#!/usr/bin/env python3
"""Generate chest loot tables for every Brasshaven structure (and the barrel supply tables of wf/barrels.py).

Each table = shared tier pools (supplies / explorer gear / treasure) + a themed pool.
Mod items (progression materials) are added once the Java side registers them.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wf.parts import USE_MOD_BLOCKS  # noqa: E402  (same switch for blocks and items)
from wf import barrels  # noqa: E402  (the modest supplies of structure barrels)
from wf import relics  # noqa: E402  (relic gear pools of the colossal structures)
from wf import colossal_gear  # noqa: E402  (vault gear pools of the newer colossal structures)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "src", "main", "resources", "data", "brasshaven", "loot_table", "chests")


def item(name, weight=10, count=(1, 1), enchant=None):
    e = {"type": "minecraft:item", "name": name if ":" in name else f"minecraft:{name}", "weight": weight}
    fns = []
    if count != (1, 1):
        fns.append({"function": "minecraft:set_count",
                    "count": {"type": "minecraft:uniform", "min": count[0], "max": count[1]}, "add": False})
    if enchant == "random":
        fns.append({"function": "minecraft:enchant_randomly"})
    elif enchant:
        fns.append({"function": "minecraft:enchant_with_levels",
                    "levels": {"type": "minecraft:uniform", "min": enchant[0], "max": enchant[1]}})
    if fns:
        e["functions"] = fns
    return e


def pool(rolls, entries, empty=0):
    if empty:
        entries = entries + [{"type": "minecraft:empty", "weight": empty}]
    return {"rolls": {"type": "minecraft:uniform", "min": rolls[0], "max": rolls[1]}, "bonus_rolls": 0.0,
            "entries": entries}


SUPPLIES = [item("bread", 15, (2, 6)), item("cooked_beef", 10, (2, 5)), item("baked_potato", 10, (2, 6)),
            item("torch", 15, (8, 24)), item("arrow", 10, (6, 16)), item("coal", 10, (3, 10)),
            item("string", 8, (2, 6)), item("leather", 8, (2, 5)), item("paper", 8, (3, 9)),
            item("iron_ingot", 8, (1, 4)), item("golden_carrot", 5, (2, 6)), item("rail", 4, (4, 12)),
            item("oak_sapling", 4, (1, 3)), item("bone", 6, (2, 5)), item("feather", 6, (2, 6))]

EXPLORER = [item("map", 10), item("compass", 8), item("spyglass", 6), item("name_tag", 5),
            item("saddle", 6), item("lead", 6, (1, 2)), item("iron_pickaxe", 6, enchant="random"),
            item("iron_sword", 6, enchant="random"), item("bow", 6, enchant="random"),
            item("iron_helmet", 4, enchant="random"), item("iron_boots", 4, enchant="random"),
            item("bundle", 4), item("experience_bottle", 8, (2, 6)), item("ender_pearl", 5, (1, 3)),
            item("book", 6, (1, 3), enchant=(5, 15)), item("firework_rocket", 5, (3, 8)),
            item("cartography_table", 2), item("recovery_compass", 1)]

TREASURE = [item("diamond", 8, (1, 3)), item("emerald", 10, (2, 6)), item("gold_ingot", 12, (2, 6)),
            item("golden_apple", 6), item("enchanted_golden_apple", 1), item("diamond_pickaxe", 3, enchant=(20, 30)),
            item("diamond_sword", 3, enchant=(20, 30)), item("book", 6, enchant=(20, 30)),
            item("totem_of_undying", 1), item("music_disc_otherside", 1), item("music_disc_pigstep", 1),
            item("netherite_upgrade_smithing_template", 2), item("heart_of_the_sea", 1),
            item("trident", 1, enchant="random")]

THEMES = {
    "guild": [item("map", 20, (1, 2)), item("compass", 10), item("writable_book", 10),
              item("cartography_table", 4), item("lantern", 8, (1, 3)), item("spyglass", 8)],
    "tower": [item("arrow", 20, (8, 24)), item("crossbow", 8, enchant="random"), item("shield", 8),
              item("iron_helmet", 6), item("chainmail_chestplate", 6), item("bell", 2)],
    "library": [item("book", 20, (1, 2), enchant=(10, 30)), item("bookshelf", 10, (1, 4)), item("ink_sac", 10, (2, 5)),
                item("writable_book", 10), item("lapis_lazuli", 15, (4, 12)), item("experience_bottle", 10, (4, 10)),
                item("enchanting_table", 2)],
    "monastery": [item("honey_bottle", 10, (1, 3)), item("candle", 15, (2, 6)), item("bell", 3),
                  item("cherry_sapling", 8, (1, 3)), item("glow_berries", 10, (3, 8)), item("golden_apple", 4)],
    "desert": [item("gold_ingot", 20, (3, 8)), item("gold_block", 4), item("emerald", 12, (2, 6)),
               item("sandstone", 10, (8, 16)), item("rotten_flesh", 10, (3, 8)), item("diamond", 5, (1, 2)),
               item("brush", 8), item("dune_armor_trim_smithing_template", 3)],
    "ocean": [item("prismarine_shard", 20, (4, 12)), item("prismarine_crystals", 15, (4, 10)),
              item("nautilus_shell", 8, (1, 3)), item("heart_of_the_sea", 2), item("trident", 2, enchant="random"),
              item("turtle_helmet", 3), item("sponge", 6, (1, 3)), item("tide_armor_trim_smithing_template", 2)],
    "witch": [item("glowstone_dust", 15, (3, 8)), item("redstone", 15, (4, 12)), item("spider_eye", 10, (2, 5)),
              item("sugar", 10, (2, 6)), item("nether_wart", 8, (2, 6)), item("blaze_powder", 5, (1, 3)),
              item("brewing_stand", 3), item("glass_bottle", 10, (3, 8)), item("phantom_membrane", 5, (1, 3))],
    "forest": [item("apple", 20, (2, 6)), item("oak_sapling", 10, (2, 4)), item("dark_oak_sapling", 8, (2, 4)),
               item("honeycomb", 10, (2, 6)), item("mushroom_stew", 5), item("bow", 8, enchant="random"),
               item("golden_apple", 4), item("brasshaven:glowwood_sapling", 6, (1, 2))],
    "sky": [item("feather", 20, (6, 16)), item("phantom_membrane", 10, (2, 4)), item("amethyst_shard", 15, (4, 10)),
            item("elytra", 1), item("firework_rocket", 15, (8, 16)), item("diamond", 6, (1, 3))],
    "mine": [item("iron_ingot", 20, (4, 10)), item("raw_gold", 12, (3, 8)), item("redstone", 15, (6, 16)),
             item("lapis_lazuli", 12, (4, 10)), item("diamond", 6, (1, 3)), item("iron_pickaxe", 8, enchant=(10, 20)),
             item("tnt", 5, (1, 3)), item("rail", 10, (8, 16)), item("powered_rail", 5, (2, 6))],
    "clockwork": [item("brasshaven:brass_ingot", 20, (3, 9)), item("brasshaven:zinc_ingot", 12, (2, 6)),
                  item("brasshaven:mithril_ingot", 5, (1, 3)), item("brasshaven:aether_crystal", 5, (1, 3)),
                  item("brasshaven:redstone_timer", 6), item("brasshaven:wireless_transmitter", 3),
                  item("brasshaven:wireless_receiver", 3), item("brasshaven:auto_harvester", 2),
                  item("brasshaven:steam_cane", 2), item("clock", 8), item("redstone", 14, (4, 12)),
                  item("copper_ingot", 14, (4, 12)), item("spyglass", 4), item("brasshaven:rustwood_sapling", 5, (1, 2))],
    "foundry": [item("brasshaven:brass_ingot", 20, (4, 10)), item("brasshaven:zinc_ingot", 14, (3, 8)),
                item("brasshaven:raw_zinc", 10, (3, 9)), item("iron_ingot", 16, (4, 12)), item("gold_ingot", 8, (2, 6)),
                item("raw_iron", 10, (4, 10)), item("coal", 12, (6, 16)), item("brasshaven:mithril_ingot", 4, (1, 3)),
                item("brasshaven:brass_pickaxe", 5, enchant="random"), item("brasshaven:brass_axe", 4, enchant="random"),
                item("brasshaven:brass_sword", 4, enchant="random"), item("brasshaven:brass_helmet", 3),
                item("brasshaven:mithril_pickaxe", 1, enchant=(15, 25)), item("anvil", 3), item("blast_furnace", 3),
                item("lava_bucket", 4), item("magma_cream", 6, (2, 5)), item("fire_charge", 6, (2, 6)),
                item("netherite_scrap", 1), item("brasshaven:rustwood_sapling", 5, (1, 2))],
    "aether": [item("brasshaven:aether_crystal", 16, (1, 4)), item("brasshaven:arcane_cloth", 10, (1, 3)),
               item("amethyst_shard", 14, (3, 9)), item("lapis_lazuli", 12, (4, 12)), item("glowstone_dust", 10, (3, 9)),
               item("redstone", 10, (4, 12)), item("copper_ingot", 10, (4, 10)), item("lightning_rod", 6, (1, 3)),
               item("end_rod", 6, (2, 6)), item("spyglass", 6), item("clock", 5), item("compass", 5),
               item("experience_bottle", 10, (3, 8)), item("book", 8, enchant=(15, 30)),
               item("brasshaven:light_staff", 2), item("brasshaven:storm_staff", 1), item("brasshaven:thunder_staff", 1),
               item("brasshaven:levitation_wand", 2), item("brasshaven:mana_amulet", 2), item("brasshaven:arcane_ring", 2)],
    "cathedral": [item("amethyst_shard", 20, (4, 12)), item("brasshaven:aether_crystal", 8, (1, 3)),
                  item("quartz", 12, (6, 16)), item("candle", 10, (2, 6)), item("lapis_lazuli", 12, (4, 12)),
                  item("book", 14, enchant=(20, 30)), item("experience_bottle", 12, (4, 10)),
                  item("echo_shard", 3, (1, 2)), item("golden_apple", 5), item("diamond", 5, (1, 3)),
                  item("amethyst_block", 6, (2, 6)), item("tinted_glass", 6, (2, 6)), item("totem_of_undying", 1),
                  item("brasshaven:arcane_ring", 2), item("brasshaven:light_staff", 2)],
    "dwarf": [item("iron_block", 10, (1, 3)), item("gold_block", 8, (1, 2)), item("diamond", 8, (2, 4)),
              item("anvil", 3), item("diamond_pickaxe", 4, enchant=(20, 30)), item("netherite_scrap", 2),
              item("smithing_table", 4), item("rib_armor_trim_smithing_template", 1)],
    "bandit": [item("emerald", 15, (2, 8)), item("crossbow", 10, enchant="random"), item("arrow", 15, (8, 16)),
               item("iron_axe", 8, enchant="random"), item("goat_horn", 4), item("totem_of_undying", 1),
               item("sentry_armor_trim_smithing_template", 2)],
    "lighthouse": [item("cod", 15, (3, 8)), item("salmon", 15, (3, 8)), item("fishing_rod", 8, enchant="random"),
                   item("oak_boat", 6), item("glowstone", 6, (2, 6)), item("sea_lantern", 5, (1, 3))],
    "jungle": [item("cocoa_beans", 15, (3, 8)), item("bamboo", 15, (6, 16)), item("emerald", 12, (2, 6)),
               item("gold_ingot", 12, (2, 6)), item("diamond", 5, (1, 3)), item("melon_seeds", 8, (2, 6)),
               item("wild_armor_trim_smithing_template", 2)],
    "ice": [item("blue_ice", 12, (2, 6)), item("packed_ice", 12, (4, 12)), item("snowball", 15, (8, 16)),
            item("spyglass", 8), item("powder_snow_bucket", 4), item("leather_boots", 6, enchant="random"),
            item("clock", 6), item("compass", 6)],
    "rune": [item("amethyst_shard", 15, (3, 8)), item("echo_shard", 3, (1, 2)), item("experience_bottle", 15, (4, 10)),
             item("book", 10, enchant=(15, 30)), item("candle", 10, (2, 6)), item("skeleton_skull", 2)],
    "ship": [item("gunpowder", 15, (3, 10)), item("map", 10), item("gold_nugget", 15, (6, 20)),
             item("emerald", 10, (2, 6)), item("compass", 6), item("diamond", 4, (1, 2)),
             item("coast_armor_trim_smithing_template", 2)],
    "ordnance": [item("tnt", 12, (1, 4)), item("gunpowder", 15, (4, 12)), item("fire_charge", 10, (2, 6)),
                 item("firework_rocket", 8, (3, 8)), item("flint_and_steel", 6), item("iron_ingot", 10, (3, 8)),
                 item("diamond", 4, (1, 2)), item("crossbow", 5, enchant=(15, 25))],
    "crystal": [item("amethyst_shard", 25, (6, 16)), item("calcite", 10, (6, 16)), item("tinted_glass", 8, (2, 6)),
                item("spyglass", 8), item("copper_ingot", 12, (4, 12)), item("diamond", 6, (1, 3))],
    "lab": [item("redstone_block", 10, (1, 3)), item("observer", 8, (1, 3)), item("comparator", 8, (1, 3)),
            item("echo_shard", 8, (1, 3)), item("sculk_catalyst", 3), item("disc_fragment_5", 6, (1, 3)),
            item("book", 6, enchant=(25, 30)), item("ward_armor_trim_smithing_template", 2),
            item("silence_armor_trim_smithing_template", 1)],
    "nether": [item("gold_ingot", 15, (3, 9)), item("quartz", 15, (6, 16)), item("magma_cream", 8, (2, 6)),
               item("blaze_rod", 10, (1, 4)), item("ghast_tear", 4, (1, 2)), item("netherite_scrap", 3),
               item("crying_obsidian", 8, (2, 6)), item("snout_armor_trim_smithing_template", 2)],
    "fortress": [item("netherite_scrap", 6, (1, 2)), item("ancient_debris", 4), item("wither_skeleton_skull", 2),
                 item("diamond", 8, (2, 4)), item("gold_block", 6, (1, 2)), item("blaze_rod", 10, (2, 5)),
                 item("netherite_upgrade_smithing_template", 3), item("rib_armor_trim_smithing_template", 2)],
    "piglin": [item("gold_block", 10, (1, 3)), item("golden_apple", 8), item("gilded_blackstone", 10, (2, 5)),
               item("crossbow", 8, enchant=(10, 20)), item("piglin_banner_pattern", 4),
               item("music_disc_pigstep", 1), item("ender_pearl", 10, (2, 4))],
    "soul": [item("soul_sand", 10, (4, 12)), item("bone_block", 10, (2, 6)), item("soul_lantern", 10, (1, 3)),
             item("blaze_rod", 8, (1, 3)), item("book", 8, enchant=(20, 30)), item("ghast_tear", 5)],
    "end": [item("ender_pearl", 15, (2, 6)), item("chorus_fruit", 15, (4, 10)), item("end_rod", 10, (2, 6)),
            item("shulker_shell", 6, (1, 2)), item("popped_chorus_fruit", 10, (4, 8)), item("diamond", 8, (2, 5)),
            item("elytra", 2), item("dragon_breath", 4, (1, 3)), item("spire_armor_trim_smithing_template", 2)],
    "citadel": [item("prismarine_shard", 10, (6, 16)), item("heart_of_the_sea", 4), item("trident", 4, enchant=(20, 30)),
                item("diamond", 10, (2, 5)), item("diamond_chestplate", 3, enchant=(20, 30)),
                item("enchanted_golden_apple", 2), item("tide_armor_trim_smithing_template", 3)],
    # batch 2 wonders
    "dwarf_city": [item("brasshaven:mithril_ingot", 18, (2, 6)), item("brasshaven:raw_mithril", 12, (3, 8)),
                   item("brasshaven:mithril_sword", 4, enchant=(15, 25)), item("brasshaven:mithril_axe", 4, enchant=(15, 25)),
                   item("brasshaven:mithril_pickaxe", 4, enchant=(15, 25)), item("brasshaven:mithril_helmet", 3, enchant=(10, 20)),
                   item("brasshaven:mithril_chestplate", 2, enchant=(10, 20)), item("diamond", 10, (1, 4)),
                   item("emerald", 12, (2, 8)), item("amethyst_shard", 10, (4, 10)), item("gold_ingot", 14, (3, 9)),
                   item("brasshaven:excavator_pickaxe", 1), item("brasshaven:telluric_hammer", 1)],
    "sylvan": [item("brasshaven:healing_staff", 3), item("brasshaven:light_staff", 3), item("brasshaven:rootmother_staff", 1),
               item("brasshaven:mana_amulet", 3), item("brasshaven:arcane_ring", 2), item("brasshaven:arcane_cloth", 10, (2, 5)),
               item("golden_apple", 8, (1, 2)), item("glow_berries", 14, (4, 12)), item("experience_bottle", 12, (3, 8)),
               item("book", 10, enchant=(15, 30)), item("bow", 6, enchant=(20, 30)), item("totem_of_undying", 1),
               item("flowering_azalea", 8, (1, 3)), item("cherry_sapling", 6, (1, 3)),
               item("brasshaven:glowwood_sapling", 8, (1, 3))],
    "inventor": [item("brasshaven:brass_ingot", 18, (4, 12)), item("brasshaven:zinc_ingot", 12, (3, 8)),
                 item("brasshaven:aether_crystal", 8, (1, 4)), item("brasshaven:steam_cane", 3), item("brasshaven:builder_wand", 3),
                 item("brasshaven:redstone_timer", 6), item("brasshaven:block_breaker", 4), item("brasshaven:block_placer", 4),
                 item("brasshaven:vacuum_hopper", 3), item("brasshaven:entity_detector", 3),
                 item("brasshaven:wireless_transmitter", 3), item("brasshaven:magnet_ring", 2), item("redstone", 14, (6, 16)),
                 item("comparator", 6, (1, 3)), item("observer", 6, (1, 3)), item("clock", 6), item("spyglass", 5)],
    "sky_isles": [item("feather", 14, (4, 12)), item("phantom_membrane", 8, (1, 4)), item("brasshaven:aether_crystal", 10, (1, 4)),
                  item("brasshaven:levitation_wand", 2), item("elytra", 1), item("firework_rocket", 12, (6, 16)),
                  item("amethyst_shard", 12, (4, 10)), item("ender_pearl", 8, (1, 3)), item("diamond", 6, (1, 3)),
                  item("brasshaven:storm_staff", 1)],
    # living oceans: diving gear, sea treasures
    "diving": [item("brasshaven:pearl", 18, (1, 3)), item("brasshaven:glow_jelly", 14, (2, 5)),
               item("brasshaven:brass_ingot", 14, (2, 6)), item("copper_ingot", 12, (3, 8)),
               item("prismarine_crystals", 12, (2, 6)), item("nautilus_shell", 8, (1, 2)),
               item("brasshaven:flippers", 3), item("brasshaven:diving_helmet", 2), item("turtle_helmet", 2),
               item("compass", 6), item("spyglass", 5), item("clock", 5), item("heart_of_the_sea", 1),
               item("brasshaven:pocket_watch", 2)],
    # the Glacier Hall of the Frost Jarls: northern war gear, mead, frost relics
    "jarl": [item("iron_axe", 10, enchant="random"), item("shield", 8), item("goat_horn", 4),
             item("honey_bottle", 10, (1, 3)), item("cooked_mutton", 12, (2, 6)), item("blue_ice", 8, (2, 6)),
             item("iron_ingot", 12, (3, 8)), item("gold_ingot", 8, (2, 5)), item("diamond", 4, (1, 2)),
             item("chainmail_chestplate", 4, enchant="random"), item("brasshaven:frost_blade", 1),
             item("brasshaven:frost_staff", 1), item("wayfinder_armor_trim_smithing_template", 1)],
}

# Progression materials from the Java side, by tier.
MOD_ITEMS = {
    "overworld": [item("brasshaven:map_fragment", 25, (1, 3)), item("brasshaven:structure_compass", 2)],
    "deep": [item("brasshaven:lithite_shard", 25, (1, 3)), item("brasshaven:map_fragment", 10, (1, 2))],
    "nether": [item("brasshaven:ancient_ember", 25, (1, 3)), item("brasshaven:lithite_shard", 8, (1, 2))],
    "end": [item("brasshaven:void_shard", 25, (1, 3)), item("brasshaven:ancient_ember", 8, (1, 2))],
}

# table -> (theme, supplies rolls, explorer rolls, treasure rolls, mod tier)
TABLES = {
    "guild_outpost": ("guild", (3, 6), (1, 3), (0, 1), "overworld"),
    "watchtower": ("tower", (2, 5), (1, 2), (0, 1), "overworld"),
    "monastery": ("monastery", (3, 6), (1, 2), (0, 1), "overworld"),
    "monastery_library": ("library", (1, 3), (1, 2), (1, 1), "overworld"),
    "oasis": ("desert", (2, 4), (1, 2), (0, 1), "overworld"),
    "desert_tomb": ("desert", (2, 4), (1, 3), (1, 2), "overworld"),
    "desert_tomb_secret": ("desert", (1, 2), (1, 2), (2, 3), "overworld"),
    "sunken_temple": ("ocean", (1, 3), (1, 2), (1, 2), "overworld"),
    "witch_hut": ("witch", (2, 4), (1, 2), (0, 1), "overworld"),
    "giant_tree": ("forest", (2, 5), (1, 2), (0, 1), "overworld"),
    "giant_tree_top": ("forest", (1, 3), (1, 3), (1, 2), "overworld"),
    "sky_island": ("sky", (1, 3), (1, 3), (1, 2), "overworld"),
    "library": ("library", (1, 4), (1, 3), (0, 1), "overworld"),
    "library_secret": ("library", (1, 2), (2, 3), (1, 2), "overworld"),
    "dwarven_mine": ("mine", (3, 6), (1, 2), (0, 1), "deep"),
    "bandit_camp": ("bandit", (2, 5), (1, 3), (0, 1), "overworld"),
    "lighthouse": ("lighthouse", (3, 6), (1, 2), (0, 1), "overworld"),
    "ziggurat": ("jungle", (2, 4), (1, 3), (1, 2), "overworld"),
    "ice_observatory": ("ice", (3, 5), (1, 2), (0, 1), "overworld"),
    "ice_observatory_lab": ("ice", (1, 3), (1, 2), (1, 1), "overworld"),
    "rune_circle": ("rune", (1, 3), (1, 2), (1, 2), "overworld"),
    "galleon_captain": ("ship", (1, 3), (2, 3), (1, 2), "overworld"),
    "galleon_cargo": ("ship", (3, 6), (0, 1), (0, 1), "overworld"),
    "dwarven_vault": ("dwarf", (1, 2), (1, 2), (1, 3), "deep"),
    "clockwork_workshop": ("clockwork", (2, 4), (0, 1), (0, 1), "overworld"),
    "clockwork_vault": ("clockwork", (1, 2), (1, 3), (2, 3), "overworld"),
    "sky_harbour": ("clockwork", (1, 3), (1, 2), (1, 2), "overworld"),
    "undercity": ("clockwork", (2, 4), (1, 2), (0, 1), "deep"),
    "undercity_vault": ("dwarf", (1, 2), (1, 3), (2, 3), "deep"),
    "crystal_grotto": ("crystal", (1, 3), (1, 2), (1, 2), "deep"),
    "foundry_forge": ("foundry", (2, 4), (1, 2), (0, 1), "overworld"),
    "foundry_vault": ("foundry", (1, 2), (1, 3), (2, 3), "overworld"),
    "walker_hold": ("inventor", (2, 5), (0, 1), (0, 1), "overworld"),
    "walker_engine": ("inventor", (1, 3), (1, 2), (0, 1), "overworld"),
    "walker_armory": ("foundry", (1, 3), (1, 2), (1, 1), "overworld"),
    "walker_vault": ("inventor", (1, 2), (1, 3), (3, 4), "overworld"),
    "necropolis_gallery": ("desert", (2, 4), (0, 1), (0, 1), "overworld"),
    "necropolis_embalmer": ("desert", (1, 3), (1, 2), (0, 1), "overworld"),
    "necropolis_treasury": ("desert", (1, 2), (1, 3), (2, 3), "overworld"),
    "necropolis_vault": ("desert", (1, 2), (1, 3), (3, 4), "overworld"),
    "colossus_arm": ("tower", (2, 5), (0, 1), (0, 1), "overworld"),
    "colossus_hall": ("rune", (1, 3), (1, 2), (0, 1), "overworld"),
    "colossus_armory": ("tower", (1, 3), (1, 2), (1, 1), "overworld"),
    "colossus_vault": ("rune", (1, 2), (1, 3), (3, 4), "overworld"),
    "ascent_foot": ("monastery", (2, 5), (0, 1), (0, 1), "overworld"),
    "ascent_shrine": ("monastery", (1, 3), (1, 2), (0, 1), "overworld"),
    "ascent_pinnacle": ("ice", (1, 3), (1, 2), (1, 2), "overworld"),
    "ascent_hermit": ("monastery", (1, 2), (1, 3), (1, 2), "overworld"),
    "ascent_vault": ("monastery", (1, 2), (1, 3), (3, 4), "overworld"),
    "abbey_town": ("monastery", (2, 5), (0, 1), (0, 1), "overworld"),
    "abbey_ramparts": ("ocean", (2, 4), (0, 1), (0, 1), "overworld"),
    "abbey_cloister": ("library", (1, 3), (1, 2), (0, 1), "overworld"),
    "abbey_knights": ("tower", (1, 3), (1, 2), (1, 1), "overworld"),
    "abbey_treasury": ("monastery", (1, 3), (1, 3), (1, 2), "overworld"),
    "abbey_reliquary": ("rune", (1, 2), (1, 2), (2, 3), "overworld"),
    "abbey_vault": ("ocean", (1, 2), (1, 3), (3, 4), "overworld"),
    "caldera_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "caldera_ramparts": ("tower", (2, 4), (0, 1), (0, 1), "overworld"),
    "caldera_barracks": ("tower", (2, 4), (0, 1), (0, 1), "overworld"),
    "caldera_armory": ("tower", (1, 3), (1, 2), (1, 1), "overworld"),
    "caldera_hall": ("monastery", (1, 3), (1, 2), (0, 1), "overworld"),
    "caldera_undercroft": ("dwarf", (1, 3), (1, 2), (1, 1), "overworld"),
    "caldera_hoard": ("rune", (1, 2), (1, 2), (2, 3), "overworld"),
    "caldera_needle": ("tower", (1, 3), (1, 3), (1, 2), "overworld"),
    "caldera_keep": ("library", (1, 3), (1, 3), (1, 2), "overworld"),
    "caldera_vault": ("tower", (1, 2), (1, 3), (3, 4), "overworld"),
    "glacier_camp": ("ice", (2, 5), (0, 1), (0, 1), "overworld"),
    "glacier_hall": ("jarl", (2, 4), (0, 1), (0, 1), "overworld"),
    "glacier_armory": ("tower", (1, 3), (1, 2), (1, 1), "overworld"),
    "glacier_skald": ("library", (1, 3), (1, 2), (0, 1), "overworld"),
    "glacier_crypt": ("jarl", (1, 3), (1, 3), (1, 2), "overworld"),
    "glacier_hoard": ("jarl", (1, 2), (1, 2), (2, 3), "overworld"),
    "glacier_vault": ("jarl", (1, 2), (1, 3), (3, 4), "overworld"),
    "kg_town": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "kg_guard": ("tower", (2, 4), (0, 1), (0, 1), "overworld"),
    "kg_girdle": ("tower", (1, 3), (1, 2), (0, 1), "overworld"),
    "kg_heart": ("library", (1, 3), (1, 2), (1, 1), "overworld"),
    "kg_watch": ("tower", (1, 3), (1, 3), (1, 1), "overworld"),
    "kg_lintel": ("monastery", (1, 3), (1, 3), (1, 2), "overworld"),
    "kg_treasury": ("rune", (1, 2), (1, 2), (2, 3), "overworld"),
    "kg_vault": ("rune", (1, 2), (1, 3), (3, 4), "overworld"),
    "dd_works": ("inventor", (2, 5), (0, 1), (0, 1), "overworld"),
    "dd_valves": ("foundry", (1, 3), (1, 2), (0, 1), "overworld"),
    "dd_control": ("inventor", (1, 3), (1, 2), (1, 1), "overworld"),
    "dd_gallery": ("monastery", (1, 3), (1, 2), (1, 1), "overworld"),
    "dd_drowned": ("ocean", (1, 3), (1, 2), (0, 1), "overworld"),
    "dd_turbine": ("inventor", (1, 3), (1, 3), (1, 2), "overworld"),
    "dd_hoard": ("ocean", (1, 2), (1, 2), (2, 3), "overworld"),
    "dd_vault": ("inventor", (1, 2), (1, 3), (3, 4), "overworld"),
    "ga_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "ga_spring": ("monastery", (2, 4), (0, 1), (0, 1), "overworld"),
    "ga_keeper": ("lighthouse", (1, 3), (1, 2), (0, 1), "overworld"),
    "ga_gallery": ("mine", (1, 3), (1, 2), (1, 1), "overworld"),
    "ga_castellum": ("library", (1, 3), (1, 2), (1, 1), "overworld"),
    "ga_valve": ("foundry", (1, 3), (1, 3), (1, 2), "overworld"),
    "ga_belfry": ("tower", (1, 3), (1, 3), (1, 2), "overworld"),
    "ga_secret": ("rune", (1, 2), (1, 2), (2, 3), "overworld"),
    "ga_vault": ("ocean", (1, 2), (1, 3), (3, 4), "overworld"),
    "dw_camp": ("lighthouse", (2, 5), (0, 1), (0, 1), "overworld"),
    "dw_crew": ("ship", (2, 5), (0, 1), (0, 1), "overworld"),
    "dw_turret": ("tower", (1, 3), (1, 2), (0, 1), "overworld"),
    "dw_bow": ("ocean", (1, 3), (1, 2), (0, 1), "overworld"),
    "dw_mess": ("ship", (1, 3), (1, 2), (0, 1), "overworld"),
    "dw_cabins": ("inventor", (1, 3), (1, 2), (1, 1), "overworld"),
    "dw_bridge": ("guild", (1, 3), (1, 2), (1, 1), "overworld"),
    "dw_engine": ("foundry", (1, 3), (1, 2), (1, 1), "overworld"),
    "dw_torpedo": ("diving", (1, 3), (1, 3), (1, 2), "overworld"),
    "dw_captain": ("ship", (1, 3), (1, 3), (1, 2), "overworld"),
    "dw_top": ("tower", (1, 2), (1, 2), (2, 3), "overworld"),
    "dw_magazine": ("ordnance", (1, 3), (1, 3), (2, 3), "overworld"),
    "dw_vault": ("ship", (1, 2), (1, 3), (3, 4), "overworld"),
    "sz_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "sz_sand": ("desert", (1, 3), (0, 1), (0, 1), "overworld"),
    "sz_offering": ("desert", (1, 3), (1, 2), (0, 1), "overworld"),
    "sz_priest": ("library", (1, 3), (1, 2), (1, 1), "overworld"),
    "sz_tomb": ("desert", (1, 3), (1, 2), (1, 2), "overworld"),
    "sz_lens": ("clockwork", (1, 3), (1, 3), (1, 2), "overworld"),
    "sz_summit": ("clockwork", (1, 2), (1, 3), (2, 3), "overworld"),
    "sz_crypt": ("desert", (1, 2), (1, 2), (2, 3), "overworld"),
    "sz_vault": ("desert", (1, 2), (1, 3), (3, 4), "overworld"),
    "cc_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "cc_ward": ("jungle", (2, 4), (0, 1), (0, 1), "overworld"),
    "cc_dwelling": ("jungle", (2, 4), (0, 1), (0, 1), "overworld"),
    "cc_gate": ("jungle", (1, 3), (1, 2), (0, 1), "overworld"),
    "cc_market": ("guild", (2, 4), (1, 2), (0, 1), "overworld"),
    "cc_highward": ("jungle", (1, 3), (1, 2), (0, 1), "overworld"),
    "cc_shrine": ("sylvan", (1, 3), (1, 2), (0, 1), "overworld"),
    "cc_loft": ("forest", (1, 3), (1, 2), (0, 1), "overworld"),
    "cc_library": ("library", (1, 3), (1, 2), (1, 1), "overworld"),
    "cc_traps": ("jungle", (1, 3), (1, 2), (1, 2), "overworld"),
    "cc_sanctum": ("jungle", (1, 2), (1, 3), (1, 2), "overworld"),
    "cc_offering": ("rune", (1, 3), (1, 2), (1, 2), "overworld"),
    "cc_crypt": ("jungle", (1, 2), (1, 2), (2, 3), "overworld"),
    "cc_cenote": ("ocean", (1, 2), (1, 3), (2, 3), "overworld"),
    "mm_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "mm_town": ("bandit", (2, 4), (0, 1), (0, 1), "overworld"),
    "mm_saloon": ("bandit", (2, 4), (1, 2), (0, 1), "overworld"),
    "mm_dwelling": ("mine", (2, 4), (0, 1), (0, 1), "overworld"),
    "mm_terrace": ("mine", (1, 3), (1, 2), (0, 1), "overworld"),
    "mm_hoist": ("clockwork", (1, 3), (1, 2), (1, 1), "overworld"),
    "mm_mill": ("foundry", (1, 3), (1, 2), (1, 1), "overworld"),
    "mm_dynamite": ("ordnance", (2, 4), (1, 2), (1, 1), "overworld"),
    "mm_haulage": ("mine", (2, 4), (1, 2), (0, 1), "overworld"),
    "mm_shaft": ("mine", (1, 3), (1, 2), (1, 1), "overworld"),
    "mm_office": ("guild", (1, 3), (1, 2), (1, 2), "overworld"),
    "mm_flooded": ("mine", (1, 2), (1, 2), (1, 2), "overworld"),
    "mm_safe": ("mine", (1, 2), (1, 2), (2, 3), "overworld"),
    "mm_vault": ("mine", (1, 2), (1, 3), (3, 4), "overworld"),
    "cc_vault": ("jungle", (1, 2), (1, 3), (3, 4), "overworld"),
    "is_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "is_chapter": ("library", (1, 3), (1, 2), (0, 1), "overworld"),
    "is_hermit": ("monastery", (1, 3), (1, 2), (0, 1), "overworld"),
    "is_refectory": ("monastery", (2, 5), (0, 1), (0, 1), "overworld"),
    "is_quarry": ("mine", (2, 4), (0, 1), (0, 1), "overworld"),
    "is_chapel": ("monastery", (1, 3), (1, 3), (1, 2), "overworld"),
    "is_ossuary": ("rune", (1, 3), (1, 2), (1, 1), "overworld"),
    "is_crypt": ("rune", (1, 3), (1, 3), (1, 2), "deep"),
    "is_unmaking": ("crystal", (1, 3), (1, 3), (1, 2), "deep"),
    "is_sanctum": ("rune", (1, 2), (1, 3), (2, 2), "deep"),
    "is_reliquary": ("crystal", (1, 2), (1, 2), (2, 3), "deep"),
    "is_vault": ("crystal", (1, 2), (1, 3), (3, 4), "deep"),
    "mire_sumps": ("witch", (2, 5), (0, 1), (0, 1), "overworld"),
    "mire_gate": ("tower", (2, 4), (0, 1), (0, 1), "overworld"),
    "mire_market": ("guild", (2, 4), (1, 2), (0, 1), "overworld"),
    "mire_smokehouse": ("forest", (2, 4), (1, 2), (0, 1), "overworld"),
    "mire_highwalk": ("witch", (1, 3), (1, 2), (1, 1), "overworld"),
    "mire_belfry": ("monastery", (1, 3), (1, 2), (1, 1), "overworld"),
    "mire_undercroft": ("ocean", (1, 3), (1, 3), (1, 2), "overworld"),
    "mire_queen": ("witch", (1, 3), (1, 3), (1, 2), "overworld"),
    "mire_hoard": ("rune", (1, 2), (1, 2), (2, 3), "overworld"),
    "mire_vault": ("witch", (1, 2), (1, 3), (3, 4), "overworld"),
    "observatory_study": ("aether", (1, 3), (1, 2), (0, 1), "overworld"),
    "observatory_lab": ("aether", (1, 3), (1, 2), (1, 1), "overworld"),
    "observatory_vault": ("aether", (1, 2), (1, 3), (2, 3), "overworld"),
    "tesla_tower": ("aether", (1, 3), (1, 2), (1, 2), "overworld"),
    "crystal_cathedral": ("cathedral", (1, 3), (1, 3), (1, 2), "deep"),
    "crystal_cathedral_vault": ("cathedral", (1, 2), (1, 3), (3, 4), "deep"),
    "sealed_lab": ("lab", (1, 3), (1, 3), (1, 2), "deep"),
    "basalt_fortress": ("fortress", (1, 3), (1, 2), (1, 2), "nether"),
    "basalt_fortress_keep": ("fortress", (1, 2), (1, 2), (2, 3), "nether"),
    "chain_bridge": ("nether", (2, 4), (1, 2), (0, 1), "nether"),
    "piglin_sanctuary": ("piglin", (1, 3), (1, 2), (1, 2), "nether"),
    "lava_foundry": ("nether", (2, 5), (1, 2), (0, 1), "nether"),
    "soul_tower": ("soul", (2, 4), (1, 2), (1, 2), "nether"),
    "piglin_market": ("piglin", (2, 4), (1, 2), (0, 1), "nether"),
    "chained_barracks": ("fortress", (2, 4), (0, 1), (0, 1), "nether"),
    "chained_forge": ("nether", (1, 3), (1, 2), (1, 1), "nether"),
    "chained_chapel": ("soul", (1, 3), (1, 3), (1, 2), "nether"),
    "chained_vault": ("piglin", (1, 2), (1, 3), (3, 4), "nether"),
    # echo_cathedral (The Echo Cathedral): better deeper, the sealed reliquary behind the organ last
    "ec_camp": ("guild", (2, 5), (0, 1), (0, 1), "deep"),
    "ec_chapel": ("monastery", (1, 3), (1, 2), (0, 1), "deep"),
    "ec_sacristy": ("cathedral", (1, 3), (1, 2), (1, 1), "deep"),
    "ec_loft": ("library", (1, 3), (1, 2), (1, 1), "deep"),
    "ec_dormitory": ("monastery", (2, 4), (1, 2), (0, 1), "deep"),
    "ec_library": ("library", (1, 3), (1, 3), (1, 2), "deep"),
    "ec_belfry": ("cathedral", (1, 2), (1, 3), (1, 2), "deep"),
    "ec_bellows": ("clockwork", (1, 3), (1, 3), (1, 2), "deep"),
    "ec_crypt": ("rune", (1, 2), (1, 3), (2, 3), "deep"),
    "ec_reliquary": ("cathedral", (1, 2), (1, 3), (3, 5), "deep"),
    # titan_forge (Forge of the Basalt Titan): better deeper, the vault in the anvil's heel last
    "tf_outpost": ("nether", (2, 4), (0, 1), (0, 1), "nether"),
    "tf_casting": ("foundry", (2, 4), (1, 2), (0, 1), "nether"),
    "tf_bellows": ("foundry", (2, 3), (1, 2), (0, 1), "nether"),
    "tf_barracks": ("fortress", (2, 4), (1, 2), (0, 1), "nether"),
    "tf_mine": ("nether", (1, 3), (1, 2), (1, 1), "nether"),
    "tf_armoury": ("fortress", (1, 3), (1, 3), (1, 1), "nether"),
    "tf_smelting": ("foundry", (1, 3), (1, 2), (1, 2), "nether"),
    "tf_drift": ("nether", (1, 2), (1, 3), (1, 2), "nether"),
    "tf_hammer": ("fortress", (1, 2), (1, 3), (2, 3), "nether"),
    "tf_eyrie": ("foundry", (1, 2), (1, 3), (2, 3), "nether"),
    "tf_vault": ("piglin", (1, 2), (1, 3), (3, 5), "nether"),
    # soul_engine (The Soul Engine): better deeper and higher, the soul reliquary behind the crankshaft boss last
    "se_camp": ("guild", (2, 5), (0, 1), (0, 1), "nether"),
    "se_hall": ("foundry", (2, 4), (1, 2), (0, 1), "nether"),
    "se_hopper": ("monastery", (2, 4), (1, 2), (0, 1), "nether"),
    "se_bunker": ("foundry", (2, 4), (1, 2), (0, 1), "nether"),
    "se_mess": ("fortress", (2, 4), (1, 2), (0, 1), "nether"),
    "se_furnace": ("foundry", (1, 3), (1, 2), (1, 1), "nether"),
    "se_gallery": ("clockwork", (1, 3), (1, 3), (1, 1), "nether"),
    "se_ossuary": ("monastery", (1, 3), (1, 2), (1, 1), "nether"),
    "se_governor": ("clockwork", (1, 3), (1, 3), (1, 2), "nether"),
    "se_crypt": ("rune", (1, 2), (1, 3), (1, 2), "nether"),
    "se_pit": ("rune", (1, 2), (1, 3), (2, 3), "nether"),
    "se_reliquary": ("piglin", (1, 2), (1, 3), (3, 5), "nether"),
    # airship_graveyard (The Airship Graveyard): field and town first, the moored ship's hold, the treasury last
    "ag_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "ag_shanty": ("bandit", (2, 4), (0, 1), (0, 1), "overworld"),
    "ag_market": ("guild", (2, 4), (1, 2), (0, 1), "overworld"),
    "ag_wreck": ("ship", (2, 4), (1, 2), (0, 1), "overworld"),
    "ag_winch": ("clockwork", (2, 4), (1, 2), (0, 1), "overworld"),
    "ag_gasworks": ("foundry", (1, 3), (1, 2), (1, 1), "overworld"),
    "ag_mast": ("sky", (1, 3), (1, 2), (1, 1), "overworld"),
    "ag_cabin": ("ship", (1, 3), (1, 2), (1, 1), "overworld"),
    "ag_bridge": ("sky", (1, 3), (1, 3), (1, 1), "overworld"),
    "ag_hold": ("ship", (2, 4), (1, 2), (1, 1), "overworld"),
    "ag_engine": ("clockwork", (1, 3), (1, 3), (1, 2), "overworld"),
    "ag_captain": ("sky", (1, 2), (1, 3), (1, 2), "overworld"),
    "ag_cache": ("sky", (1, 2), (1, 3), (2, 3), "overworld"),
    "ag_treasury": ("sky", (1, 2), (1, 3), (3, 5), "overworld"),
    "void_observatory": ("end", (1, 3), (1, 2), (1, 2), "end"),
    "chorus_garden": ("end", (2, 4), (1, 2), (0, 1), "end"),
    "end_archive": ("end", (1, 3), (1, 3), (1, 2), "end"),
    "end_archive_top": ("end", (1, 2), (1, 2), (2, 3), "end"),
    "void_ship": ("end", (2, 4), (1, 2), (1, 2), "end"),
    "void_nest": ("end", (1, 2), (1, 2), (2, 4), "end"),
    "halo_islet": ("end", (2, 4), (0, 1), (0, 1), "end"),
    "halo_observatory": ("end", (1, 3), (1, 2), (0, 1), "end"),
    "halo_library": ("end", (1, 3), (1, 3), (1, 1), "end"),
    "halo_reliquary": ("end", (1, 2), (1, 2), (1, 2), "end"),
    "halo_bell": ("end", (1, 3), (1, 2), (1, 1), "end"),
    "halo_gate": ("end", (1, 3), (1, 2), (1, 2), "end"),
    "halo_crypt": ("end", (1, 2), (1, 3), (2, 3), "end"),
    "halo_vault": ("end", (1, 2), (1, 3), (3, 4), "end"),
    # cloud_pagoda (The Cloud Pagoda): better higher, the vault behind the top-tier boss last
    "cp_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "cp_garden": ("monastery", (2, 5), (0, 1), (0, 1), "overworld"),
    "cp_bell": ("monastery", (1, 3), (1, 2), (0, 1), "overworld"),
    "cp_hall": ("monastery", (1, 3), (1, 2), (0, 1), "overworld"),
    "cp_shrine": ("clockwork", (1, 3), (1, 2), (1, 1), "overworld"),
    "cp_dojo": ("tower", (1, 3), (1, 2), (1, 1), "overworld"),
    "cp_library": ("library", (1, 3), (1, 2), (1, 1), "overworld"),
    "cp_armoury": ("tower", (1, 3), (1, 3), (1, 1), "overworld"),
    "cp_meditation": ("monastery", (1, 3), (1, 2), (1, 2), "overworld"),
    "cp_orrery": ("clockwork", (1, 3), (1, 3), (1, 2), "overworld"),
    "cp_grotto": ("rune", (1, 2), (1, 2), (2, 3), "overworld"),
    "cp_abbot": ("library", (1, 2), (1, 3), (2, 3), "overworld"),
    "cp_chimes": ("clockwork", (1, 2), (1, 3), (2, 3), "overworld"),
    "cp_vault": ("clockwork", (1, 2), (1, 3), (3, 4), "overworld"),
    # icebound_fleet (The Icebound Fleet): camps on the ice first, the supply ships, the icebreaker's decks, the strongroom last
    "if_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "if_whale": ("ocean", (2, 4), (0, 1), (0, 1), "overworld"),
    "if_hub": ("ice", (2, 4), (0, 1), (0, 1), "overworld"),
    "if_derrick": ("mine", (2, 4), (1, 2), (0, 1), "overworld"),
    "if_kennels": ("ice", (2, 4), (1, 2), (0, 1), "overworld"),
    "if_hold": ("ship", (2, 4), (1, 2), (0, 1), "overworld"),
    "if_berths": ("ship", (2, 4), (1, 2), (0, 1), "overworld"),
    "if_chart": ("library", (1, 3), (1, 2), (1, 1), "overworld"),
    "if_bunker": ("foundry", (2, 4), (1, 2), (1, 1), "overworld"),
    "if_boiler": ("clockwork", (1, 3), (1, 2), (1, 1), "overworld"),
    "if_crew": ("ship", (1, 3), (1, 2), (1, 1), "overworld"),
    "if_engineers": ("inventor", (1, 3), (1, 3), (1, 1), "overworld"),
    "if_officers": ("library", (1, 3), (1, 3), (1, 2), "overworld"),
    "if_crowsnest": ("ice", (1, 2), (1, 3), (1, 2), "overworld"),
    "if_captain": ("ship", (1, 2), (1, 3), (2, 3), "overworld"),
    "if_strongroom": ("ice", (1, 2), (1, 3), (3, 5), "overworld"),
    # clockwork_asylum (The Clockwork Asylum): yard and cemetery first, wards and tower floors, the director's office last
    "asy_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "asy_gate": ("tower", (2, 4), (0, 1), (0, 1), "overworld"),
    "asy_station": ("clockwork", (2, 4), (1, 2), (0, 1), "overworld"),
    "asy_cemetery": ("monastery", (2, 4), (1, 2), (0, 1), "overworld"),
    "asy_hall": ("library", (1, 3), (1, 2), (0, 1), "overworld"),
    "asy_cells": ("bandit", (1, 3), (1, 2), (1, 1), "overworld"),
    "asy_ward": ("clockwork", (1, 3), (1, 2), (1, 1), "overworld"),
    "asy_chapel": ("cathedral", (1, 3), (1, 2), (1, 1), "overworld"),
    "asy_greenhouse": ("forest", (2, 4), (1, 2), (1, 1), "overworld"),
    "asy_laundry": ("guild", (1, 3), (1, 2), (1, 1), "overworld"),
    "asy_theatre": ("lab", (1, 3), (1, 3), (1, 2), "overworld"),
    "asy_archive": ("library", (1, 3), (1, 3), (1, 2), "overworld"),
    "asy_baths": ("lab", (1, 3), (1, 3), (1, 2), "overworld"),
    "asy_crypt": ("rune", (1, 2), (1, 3), (2, 3), "overworld"),
    "asy_mechanism": ("clockwork", (1, 3), (1, 3), (1, 2), "overworld"),
    "asy_mechanism_high": ("clockwork", (1, 2), (1, 3), (2, 3), "overworld"),
    "asy_office": ("inventor", (1, 2), (1, 3), (3, 5), "overworld"),
    # verdant_arboretum (The Sunken Arboretum): better deeper, camp and shore first, the herbarium vault behind the boss last
    "va_camp": ("guild", (2, 5), (0, 1), (0, 1), "deep"),
    "va_station": ("ocean", (2, 4), (0, 1), (0, 1), "deep"),
    "va_deck": ("sylvan", (2, 4), (1, 2), (0, 1), "deep"),
    "va_grotto": ("forest", (1, 3), (1, 2), (0, 1), "deep"),
    "va_greenhouse": ("sylvan", (2, 4), (1, 2), (1, 1), "deep"),
    "va_seedvault": ("forest", (1, 3), (1, 2), (1, 1), "deep"),
    "va_lab": ("lab", (1, 3), (1, 3), (1, 2), "deep"),
    "va_pump": ("foundry", (1, 3), (1, 3), (1, 2), "deep"),
    "va_lift": ("clockwork", (1, 3), (1, 2), (1, 1), "deep"),
    "va_maze": ("witch", (1, 3), (1, 3), (1, 2), "deep"),
    "va_cornice": ("inventor", (1, 2), (1, 3), (2, 3), "deep"),
    "va_herbarium": ("library", (1, 2), (1, 3), (3, 5), "deep"),
    # spore_refinery (The Spore Refinery): camp and yard first, the halls, cellars and lofts, the lab, the vault last
    "sr_camp": ("guild", (2, 5), (0, 1), (0, 1), "overworld"),
    "sr_yard": ("foundry", (2, 4), (0, 1), (0, 1), "overworld"),
    "sr_press": ("foundry", (2, 4), (1, 2), (0, 1), "overworld"),
    "sr_gallery": ("guild", (2, 4), (1, 2), (1, 1), "overworld"),
    "sr_ferment": ("witch", (1, 3), (1, 2), (1, 1), "overworld"),
    "sr_distillery": ("lab", (1, 3), (1, 2), (1, 1), "overworld"),
    "sr_cellar": ("witch", (1, 3), (1, 3), (1, 2), "overworld"),
    "sr_loft": ("forest", (1, 3), (1, 3), (1, 2), "overworld"),
    "sr_lab": ("lab", (1, 2), (1, 3), (2, 3), "overworld"),
    "sr_gills": ("inventor", (1, 2), (1, 3), (2, 3), "overworld"),
    "sr_vault": ("lab", (1, 2), (1, 3), (3, 5), "overworld"),
    # timber_fortress (The Timber Fortress): camp, gate and yard first, the works, the keep floors, the strongroom last
    "tf_camp": ("forest", (2, 5), (0, 1), (0, 1), "overworld"),
    "tf_gate": ("tower", (2, 4), (0, 1), (0, 1), "overworld"),
    "tf_yard": ("guild", (2, 4), (0, 1), (0, 1), "overworld"),
    "tf_sawmill": ("foundry", (2, 4), (1, 2), (0, 1), "overworld"),
    "tf_mess": ("guild", (2, 4), (1, 2), (0, 1), "overworld"),
    "tf_kilns": ("mine", (1, 3), (1, 2), (1, 1), "overworld"),
    "tf_lodge": ("bandit", (1, 3), (1, 2), (1, 1), "overworld"),
    "tf_headworks": ("clockwork", (1, 3), (1, 2), (1, 1), "overworld"),
    "tf_armoury": ("jarl", (1, 3), (1, 3), (1, 2), "overworld"),
    "tf_hall": ("jarl", (1, 3), (1, 3), (1, 2), "overworld"),
    "tf_maproom": ("library", (1, 2), (1, 3), (2, 3), "overworld"),
    "tf_strongroom": ("inventor", (1, 2), (1, 3), (3, 5), "overworld"),
    # abyssal_station (The Abyssal Station): better deeper, the tower camp first, the domes, the drill shaft, the specimen vault last
    "abs_camp": ("ship", (2, 4), (0, 1), (0, 1), "overworld"),
    "abs_lock": ("diving", (2, 4), (0, 1), (0, 1), "overworld"),
    "abs_concourse": ("ocean", (2, 4), (1, 2), (0, 1), "overworld"),
    "abs_hydro": ("sylvan", (2, 4), (1, 2), (0, 1), "overworld"),
    "abs_crew": ("ship", (2, 4), (1, 2), (1, 1), "overworld"),
    "abs_cabin": ("inventor", (1, 3), (1, 2), (1, 1), "overworld"),
    "abs_aquarium": ("lab", (1, 3), (1, 2), (1, 1), "overworld"),
    "abs_whale": ("ocean", (1, 3), (1, 2), (1, 1), "overworld"),
    "abs_observation": ("diving", (1, 3), (1, 3), (1, 2), "overworld"),
    "abs_tube": ("diving", (1, 3), (1, 3), (1, 2), "overworld"),
    "abs_boiler": ("foundry", (1, 3), (1, 3), (1, 2), "overworld"),
    "abs_control": ("inventor", (1, 2), (1, 3), (2, 3), "overworld"),
    "abs_shaft": ("mine", (1, 2), (1, 3), (2, 3), "overworld"),
    "abs_vault": ("diving", (1, 2), (1, 3), (3, 5), "overworld"),
    # starfall_library (The Starfall Library): better higher and deeper, the forbidden stacks behind the boss last
    "sl_camp": ("end", (2, 4), (0, 1), (0, 1), "end"),
    "sl_maproom": ("library", (2, 4), (1, 2), (0, 1), "end"),
    "sl_gallery": ("end", (2, 3), (1, 2), (0, 1), "end"),
    "sl_stacks": ("library", (1, 3), (1, 2), (1, 1), "end"),
    "sl_scriptorium": ("library", (1, 3), (1, 3), (1, 1), "end"),
    "sl_index": ("library", (1, 3), (1, 3), (1, 2), "end"),
    "sl_gallery_high": ("end", (1, 3), (1, 3), (1, 2), "end"),
    "sl_observatory": ("end", (1, 2), (1, 3), (2, 3), "end"),
    "sl_meteorite": ("end", (1, 2), (1, 3), (2, 3), "end"),
    "sl_vault": ("library", (1, 2), (1, 3), (3, 5), "end"),
    # hollow_moon (The Hollow Moon): better deeper inside the moon, the core reliquary behind the boss last
    "hm_camp": ("end", (2, 4), (0, 1), (0, 1), "end"),
    "hm_breach": ("end", (2, 3), (1, 2), (0, 1), "end"),
    "hm_gardens": ("lab", (2, 3), (1, 2), (0, 1), "end"),
    "hm_hub": ("clockwork", (1, 3), (1, 2), (1, 1), "end"),
    "hm_crypt": ("clockwork", (1, 3), (1, 3), (1, 1), "end"),
    "hm_starchart": ("library", (1, 3), (1, 3), (1, 2), "end"),
    "hm_workshop": ("inventor", (1, 3), (1, 3), (1, 2), "end"),
    "hm_rings": ("clockwork", (1, 2), (1, 3), (2, 3), "end"),
    "hm_reliquary": ("end", (1, 2), (1, 3), (3, 5), "end"),
    "citadel_common": ("citadel", (3, 6), (1, 2), (0, 1), "overworld"),
    "citadel_armory": ("citadel", (1, 3), (2, 4), (0, 1), "overworld"),
    "citadel_library": ("library", (1, 3), (1, 3), (1, 1), "overworld"),
    "citadel_shrine": ("ocean", (1, 2), (1, 2), (1, 2), "overworld"),
    "citadel_arena": ("citadel", (1, 2), (1, 2), (1, 2), "overworld"),
    "citadel_vault": ("citadel", (1, 2), (1, 2), (3, 5), "overworld"),
    # standalone dungeons: common rooms, treasure rooms / secret chambers, the reward vault past the boss
    "catacombs": ("monastery", (2, 4), (1, 2), (0, 1), "overworld"),
    "catacombs_treasure": ("monastery", (1, 2), (1, 3), (1, 2), "overworld"),
    "catacombs_reward": ("monastery", (1, 2), (1, 2), (3, 4), "overworld"),
    "hypogeum": ("desert", (2, 4), (1, 2), (0, 1), "overworld"),
    "hypogeum_treasure": ("desert", (1, 2), (1, 3), (1, 2), "overworld"),
    "hypogeum_reward": ("desert", (1, 2), (1, 2), (3, 4), "overworld"),
    "lithite_well": ("dwarf", (2, 4), (1, 2), (0, 1), "deep"),
    "lithite_well_treasure": ("dwarf", (1, 2), (1, 3), (1, 2), "deep"),
    "lithite_well_reward": ("dwarf", (1, 2), (1, 2), (3, 4), "deep"),
    "void_crypt": ("end", (2, 4), (1, 2), (0, 1), "end"),
    "void_crypt_treasure": ("end", (1, 2), (1, 3), (1, 2), "end"),
    "void_crypt_reward": ("end", (1, 2), (1, 2), (3, 5), "end"),
    # batch 2 wonders
    "dwarven_city": ("dwarf_city", (2, 4), (1, 2), (0, 1), "deep"),
    "dwarven_city_forge": ("dwarf_city", (1, 3), (1, 2), (0, 1), "deep"),
    "dwarven_city_vault": ("dwarf_city", (1, 2), (1, 2), (3, 5), "deep"),
    "sylvan_palace": ("sylvan", (2, 4), (1, 2), (0, 1), "overworld"),
    "sylvan_palace_royal": ("sylvan", (1, 2), (1, 3), (2, 3), "overworld"),
    "inventor_manor": ("inventor", (2, 4), (1, 2), (0, 1), "overworld"),
    "inventor_lab": ("inventor", (1, 2), (1, 3), (2, 3), "overworld"),
    "sky_isles": ("sky_isles", (1, 3), (1, 2), (0, 1), "overworld"),
    "sky_isles_shrine": ("sky_isles", (1, 2), (1, 2), (2, 4), "overworld"),
    # living oceans: small sea-floor structures
    "sunken_submarine": ("diving", (1, 3), (1, 2), (0, 1), "overworld"),
    "diving_bell": ("diving", (2, 4), (0, 1), (0, 1), "overworld"),
    "coral_shrine": ("ocean", (1, 2), (1, 2), (0, 1), "overworld"),
    "shipwreck_debris": ("ship", (2, 4), (1, 2), (0, 1), "overworld"),
}


def table(name, spec):
    theme, sup, exp, tre, tier = spec
    pools = [pool((2, 4), THEMES[theme])]
    if sup[1]:
        pools.append(pool(sup, SUPPLIES))
    if exp[1]:
        pools.append(pool(exp, EXPLORER))
    if tre[1]:
        pools.append(pool(tre, TREASURE))
    if USE_MOD_BLOCKS:
        pools.append(pool((1, 2), MOD_ITEMS[tier]))
        pools += relics.loot_pools(name)  # relic gear of the colossal structures, rarer deeper in
        pools += colossal_gear.loot_pools(name)  # vault gear: deep chests and vaults only
    return {"type": "minecraft:chest", "pools": pools, "random_sequence": f"brasshaven:chests/{name}"}


def main():
    os.makedirs(OUT, exist_ok=True)
    for name, spec in TABLES.items():
        with open(os.path.join(OUT, f"{name}.json"), "w") as f:
            json.dump(table(name, spec), f, indent=2)
            f.write("\n")
    for kind in barrels.KINDS:
        with open(os.path.join(OUT, f"barrel_{kind}.json"), "w") as f:
            json.dump(barrels.table_json(kind), f, indent=2)
            f.write("\n")
    print(f"{len(TABLES)} loot tables written, {len(barrels.KINDS)} barrel supply tables")


if __name__ == "__main__":
    main()
