#!/usr/bin/env python3
"""Generate Java constants shared with the data generators (structure catalog + quest chapters)."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wf import defs  # noqa: E402
import wf.structures  # noqa: E402,F401

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "src", "main", "java", "com", "wayfarers", "generated", "GeneratedContent.java")
QUESTS = os.path.join(ROOT, "src", "main", "resources", "data", "wayfarers", "quests.json")


def main():
    chapters = json.load(open(QUESTS))
    lines = [
        "package com.wayfarers.generated;",
        "",
        "import java.util.List;",
        "",
        "/** GENERATED by tools/gen_java.py — do not edit by hand. */",
        "public final class GeneratedContent {",
        "    public record StructureInfo(String id, String dimension) {}",
        "",
        "    public record Chapter(String id, List<String> quests) {}",
        "",
        "    public static final List<StructureInfo> STRUCTURES = List.of(",
    ]
    entries = [f'            new StructureInfo("{s.id}", "{s.dimension}")' for s in defs.STRUCTURES]
    lines.append(",\n".join(entries))
    lines += ["    );", "", "    public static final List<Chapter> CHAPTERS = List.of("]
    ch = []
    for cid, quests in chapters.items():
        qs = ", ".join(f'"{q}"' for q in quests)
        ch.append(f'            new Chapter("{cid}", List.of({qs}))')
    lines.append(",\n".join(ch))
    lines += ["    );", "", "    private GeneratedContent() {}", "}", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
